//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyReserva
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ReservaYoga")]
    public partial class ReservaDC : object
    {
        
        private string Cod_resvField;
        
        private string EstRevField;
        
        private short Est_resvField;
        
        private System.DateTime Fec_Ult_ModField;
        
        private System.DateTime Fec_regField;
        
        private System.DateTime Fec_resvField;
        
        private short Id_Clase_ProgField;
        
        private short Id_ClienteField;
        
        private string NombreField;
        
        private string ObservacionField;
        
        private string Usu_Ult_ModField;
        
        private string Usu_regField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_resv
        {
            get
            {
                return this.Cod_resvField;
            }
            set
            {
                this.Cod_resvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstRev
        {
            get
            {
                return this.EstRevField;
            }
            set
            {
                this.EstRevField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_resv
        {
            get
            {
                return this.Est_resvField;
            }
            set
            {
                this.Est_resvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod
        {
            get
            {
                return this.Fec_Ult_ModField;
            }
            set
            {
                this.Fec_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_reg
        {
            get
            {
                return this.Fec_regField;
            }
            set
            {
                this.Fec_regField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_resv
        {
            get
            {
                return this.Fec_resvField;
            }
            set
            {
                this.Fec_resvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Clase_Prog
        {
            get
            {
                return this.Id_Clase_ProgField;
            }
            set
            {
                this.Id_Clase_ProgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Cliente
        {
            get
            {
                return this.Id_ClienteField;
            }
            set
            {
                this.Id_ClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion
        {
            get
            {
                return this.ObservacionField;
            }
            set
            {
                this.ObservacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod
        {
            get
            {
                return this.Usu_Ult_ModField;
            }
            set
            {
                this.Usu_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_reg
        {
            get
            {
                return this.Usu_regField;
            }
            set
            {
                this.Usu_regField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyReserva.IServicioReserva")]
    public interface IServicioReserva
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ContarReservasTotales", ReplyAction="http://tempuri.org/IServicioReserva/ContarReservasTotalesResponse")]
        short ContarReservasTotales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ContarReservasTotales", ReplyAction="http://tempuri.org/IServicioReserva/ContarReservasTotalesResponse")]
        System.Threading.Tasks.Task<short> ContarReservasTotalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ContarReservasCliente", ReplyAction="http://tempuri.org/IServicioReserva/ContarReservasClienteResponse")]
        short ContarReservasCliente(short strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ContarReservasCliente", ReplyAction="http://tempuri.org/IServicioReserva/ContarReservasClienteResponse")]
        System.Threading.Tasks.Task<short> ContarReservasClienteAsync(short strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ObtenerFechaReservaPorCodigo", ReplyAction="http://tempuri.org/IServicioReserva/ObtenerFechaReservaPorCodigoResponse")]
        System.Nullable<System.DateTime> ObtenerFechaReservaPorCodigo(string codigoReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ObtenerFechaReservaPorCodigo", ReplyAction="http://tempuri.org/IServicioReserva/ObtenerFechaReservaPorCodigoResponse")]
        System.Threading.Tasks.Task<System.Nullable<System.DateTime>> ObtenerFechaReservaPorCodigoAsync(string codigoReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarReservaClienteFechas", ReplyAction="http://tempuri.org/IServicioReserva/ListarReservaClienteFechasResponse")]
        System.Collections.Generic.List<ProxyReserva.ReservaDC> ListarReservaClienteFechas(short strCodigo, System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarReservaClienteFechas", ReplyAction="http://tempuri.org/IServicioReserva/ListarReservaClienteFechasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyReserva.ReservaDC>> ListarReservaClienteFechasAsync(short strCodigo, System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/InsertarReserva", ReplyAction="http://tempuri.org/IServicioReserva/InsertarReservaResponse")]
        bool InsertarReserva(ProxyReserva.ReservaDC objReservaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/InsertarReserva", ReplyAction="http://tempuri.org/IServicioReserva/InsertarReservaResponse")]
        System.Threading.Tasks.Task<bool> InsertarReservaAsync(ProxyReserva.ReservaDC objReservaDC);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioReservaChannel : ProxyReserva.IServicioReserva, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioReservaClient : System.ServiceModel.ClientBase<ProxyReserva.IServicioReserva>, ProxyReserva.IServicioReserva
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioReservaClient() : 
                base(ServicioReservaClient.GetDefaultBinding(), ServicioReservaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioReserva.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioReservaClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioReservaClient.GetBindingForEndpoint(endpointConfiguration), ServicioReservaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioReservaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioReservaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioReservaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioReservaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioReservaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public short ContarReservasTotales()
        {
            return base.Channel.ContarReservasTotales();
        }
        
        public System.Threading.Tasks.Task<short> ContarReservasTotalesAsync()
        {
            return base.Channel.ContarReservasTotalesAsync();
        }
        
        public short ContarReservasCliente(short strCodigo)
        {
            return base.Channel.ContarReservasCliente(strCodigo);
        }
        
        public System.Threading.Tasks.Task<short> ContarReservasClienteAsync(short strCodigo)
        {
            return base.Channel.ContarReservasClienteAsync(strCodigo);
        }
        
        public System.Nullable<System.DateTime> ObtenerFechaReservaPorCodigo(string codigoReserva)
        {
            return base.Channel.ObtenerFechaReservaPorCodigo(codigoReserva);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<System.DateTime>> ObtenerFechaReservaPorCodigoAsync(string codigoReserva)
        {
            return base.Channel.ObtenerFechaReservaPorCodigoAsync(codigoReserva);
        }
        
        public System.Collections.Generic.List<ProxyReserva.ReservaDC> ListarReservaClienteFechas(short strCodigo, System.DateTime fecIni, System.DateTime fecFin)
        {
            return base.Channel.ListarReservaClienteFechas(strCodigo, fecIni, fecFin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyReserva.ReservaDC>> ListarReservaClienteFechasAsync(short strCodigo, System.DateTime fecIni, System.DateTime fecFin)
        {
            return base.Channel.ListarReservaClienteFechasAsync(strCodigo, fecIni, fecFin);
        }
        
        public bool InsertarReserva(ProxyReserva.ReservaDC objReservaDC)
        {
            return base.Channel.InsertarReserva(objReservaDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarReservaAsync(ProxyReserva.ReservaDC objReservaDC)
        {
            return base.Channel.InsertarReservaAsync(objReservaDC);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioReserva))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioReserva))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ReservaYoga/ServicioReserva/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioReservaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioReserva);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioReservaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioReserva);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioReserva,
        }
    }
}
