//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ReservaYoga
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Cliente()
        {
            this.Tb_Reserva = new HashSet<Tb_Reserva>();
        }
    
        public int Id_Cliente { get; set; }
        public string Nombres { get; set; }
        public string ApePaterno { get; set; }
        public string ApeMaterno { get; set; }
        public string Correo { get; set; }
        public string Tel_cli { get; set; }
        public string Dir_cli { get; set; }
        public string Dni_cli { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> Fec_nac { get; set; }
        public Nullable<int> Est_cli { get; set; }
        public string Id_Ubigeo { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<System.DateTime> Fec_reg { get; set; }
        public string Usu_reg { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Reserva> Tb_Reserva { get; set; }
        public virtual Tb_Ubigeo Tb_Ubigeo { get; set; }
    }
}
