//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ReservaYoga
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaCliente
    {
        public int Id_Cliente { get; set; }
        public string Nombres { get; set; }
        public string ApePaterno { get; set; }
        public string ApeMaterno { get; set; }
        public string Correo { get; set; }
        public string Tel_cli { get; set; }
        public string Dir_cli { get; set; }
        public string Dni_cli { get; set; }
        public string Genero { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> Fec_nac { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<int> Est_cli { get; set; }
        public string Estado { get; set; }
        public string Id_Ubigeo { get; set; }
        public string Departamento { get; set; }
        public string Provincia { get; set; }
        public string Distrito { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<System.DateTime> Fec_reg { get; set; }
        public string Usu_Reg { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
    }
}
