//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ReservaYoga
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaClaseProgramada
    {
        public int Id_Clase_Prog { get; set; }
        public Nullable<int> Id_Salon { get; set; }
        public string Salon { get; set; }
        public Nullable<int> Capacidad { get; set; }
        public string Id_Inst_Disp { get; set; }
        public string Id_Instructor { get; set; }
        public string Nombre_Instructor { get; set; }
        public string ApePaterno { get; set; }
        public string ApeMaterno { get; set; }
        public string Disciplina { get; set; }
        public string Intensidad { get; set; }
        public System.DateTime Fec_Clase { get; set; }
        public Nullable<System.DateTime> Hora_Emp { get; set; }
        public Nullable<System.DateTime> Hora_Term { get; set; }
        public string Usu_Reg { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public Nullable<int> Est_clase { get; set; }
        public string Estado { get; set; }
    }
}
