//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ReservaYoga
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaDisciplina
    {
        public string Cod_disp { get; set; }
        public string Nombre { get; set; }
        public string Duracion { get; set; }
        public string Intensidad { get; set; }
        public decimal Precio { get; set; }
        public string Categoria { get; set; }
    }
}
