//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_ConsultaInstructor.ProxyReserva {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ReservaYoga")]
    [System.SerializableAttribute()]
    public partial class ReservaDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_resvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstRevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Est_resvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_regField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_resvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Id_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_regField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_resv {
            get {
                return this.Cod_resvField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_resvField, value) != true)) {
                    this.Cod_resvField = value;
                    this.RaisePropertyChanged("Cod_resv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstRev {
            get {
                return this.EstRevField;
            }
            set {
                if ((object.ReferenceEquals(this.EstRevField, value) != true)) {
                    this.EstRevField = value;
                    this.RaisePropertyChanged("EstRev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_resv {
            get {
                return this.Est_resvField;
            }
            set {
                if ((this.Est_resvField.Equals(value) != true)) {
                    this.Est_resvField = value;
                    this.RaisePropertyChanged("Est_resv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_reg {
            get {
                return this.Fec_regField;
            }
            set {
                if ((this.Fec_regField.Equals(value) != true)) {
                    this.Fec_regField = value;
                    this.RaisePropertyChanged("Fec_reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_resv {
            get {
                return this.Fec_resvField;
            }
            set {
                if ((this.Fec_resvField.Equals(value) != true)) {
                    this.Fec_resvField = value;
                    this.RaisePropertyChanged("Fec_resv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Cliente {
            get {
                return this.Id_ClienteField;
            }
            set {
                if ((this.Id_ClienteField.Equals(value) != true)) {
                    this.Id_ClienteField = value;
                    this.RaisePropertyChanged("Id_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_reg {
            get {
                return this.Usu_regField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_regField, value) != true)) {
                    this.Usu_regField = value;
                    this.RaisePropertyChanged("Usu_reg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyReserva.IServicioReserva")]
    public interface IServicioReserva {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ContarReservasTotales", ReplyAction="http://tempuri.org/IServicioReserva/ContarReservasTotalesResponse")]
        short ContarReservasTotales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ContarReservasTotales", ReplyAction="http://tempuri.org/IServicioReserva/ContarReservasTotalesResponse")]
        System.Threading.Tasks.Task<short> ContarReservasTotalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ContarReservasCliente", ReplyAction="http://tempuri.org/IServicioReserva/ContarReservasClienteResponse")]
        short ContarReservasCliente(short strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ContarReservasCliente", ReplyAction="http://tempuri.org/IServicioReserva/ContarReservasClienteResponse")]
        System.Threading.Tasks.Task<short> ContarReservasClienteAsync(short strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ObtenerFechaReservaPorCodigo", ReplyAction="http://tempuri.org/IServicioReserva/ObtenerFechaReservaPorCodigoResponse")]
        System.Nullable<System.DateTime> ObtenerFechaReservaPorCodigo(string codigoReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ObtenerFechaReservaPorCodigo", ReplyAction="http://tempuri.org/IServicioReserva/ObtenerFechaReservaPorCodigoResponse")]
        System.Threading.Tasks.Task<System.Nullable<System.DateTime>> ObtenerFechaReservaPorCodigoAsync(string codigoReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarReservaClienteFechas", ReplyAction="http://tempuri.org/IServicioReserva/ListarReservaClienteFechasResponse")]
        WEB_ConsultaInstructor.ProxyReserva.ReservaDC[] ListarReservaClienteFechas(short strCodigo, System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarReservaClienteFechas", ReplyAction="http://tempuri.org/IServicioReserva/ListarReservaClienteFechasResponse")]
        System.Threading.Tasks.Task<WEB_ConsultaInstructor.ProxyReserva.ReservaDC[]> ListarReservaClienteFechasAsync(short strCodigo, System.DateTime fecIni, System.DateTime fecFin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioReservaChannel : WEB_ConsultaInstructor.ProxyReserva.IServicioReserva, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioReservaClient : System.ServiceModel.ClientBase<WEB_ConsultaInstructor.ProxyReserva.IServicioReserva>, WEB_ConsultaInstructor.ProxyReserva.IServicioReserva {
        
        public ServicioReservaClient() {
        }
        
        public ServicioReservaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioReservaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReservaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReservaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public short ContarReservasTotales() {
            return base.Channel.ContarReservasTotales();
        }
        
        public System.Threading.Tasks.Task<short> ContarReservasTotalesAsync() {
            return base.Channel.ContarReservasTotalesAsync();
        }
        
        public short ContarReservasCliente(short strCodigo) {
            return base.Channel.ContarReservasCliente(strCodigo);
        }
        
        public System.Threading.Tasks.Task<short> ContarReservasClienteAsync(short strCodigo) {
            return base.Channel.ContarReservasClienteAsync(strCodigo);
        }
        
        public System.Nullable<System.DateTime> ObtenerFechaReservaPorCodigo(string codigoReserva) {
            return base.Channel.ObtenerFechaReservaPorCodigo(codigoReserva);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<System.DateTime>> ObtenerFechaReservaPorCodigoAsync(string codigoReserva) {
            return base.Channel.ObtenerFechaReservaPorCodigoAsync(codigoReserva);
        }
        
        public WEB_ConsultaInstructor.ProxyReserva.ReservaDC[] ListarReservaClienteFechas(short strCodigo, System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ListarReservaClienteFechas(strCodigo, fecIni, fecFin);
        }
        
        public System.Threading.Tasks.Task<WEB_ConsultaInstructor.ProxyReserva.ReservaDC[]> ListarReservaClienteFechasAsync(short strCodigo, System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ListarReservaClienteFechasAsync(strCodigo, fecIni, fecFin);
        }
    }
}
