//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ReservaYoga
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ReservaYogaEntities : DbContext
    {
        public ReservaYogaEntities()
            : base("name=ReservaYogaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Administrador> Tb_Administrador { get; set; }
        public virtual DbSet<Tb_Categoria> Tb_Categoria { get; set; }
        public virtual DbSet<Tb_Clase_Programada> Tb_Clase_Programada { get; set; }
        public virtual DbSet<Tb_Cliente> Tb_Cliente { get; set; }
        public virtual DbSet<Tb_Disciplina> Tb_Disciplina { get; set; }
        public virtual DbSet<Tb_Instructor> Tb_Instructor { get; set; }
        public virtual DbSet<Tb_Instructor_Disciplina> Tb_Instructor_Disciplina { get; set; }
        public virtual DbSet<Tb_Reserva> Tb_Reserva { get; set; }
        public virtual DbSet<Tb_Salon> Tb_Salon { get; set; }
        public virtual DbSet<Tb_Ubigeo> Tb_Ubigeo { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
    
        public virtual int usp_ActualizarCliente(Nullable<int> vcod, string vNombres, string vApePaterno, string vApeMaterno, string vCorreo, string vTel_cli, string vDir_cli, string vDni_cli, string vSexo, Nullable<System.DateTime> vFec_nac, Nullable<int> vEst_cli, string vId_Ubigeo, string vUsu_Ult_Mod)
        {
            var vcodParameter = vcod.HasValue ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(int));
    
            var vNombresParameter = vNombres != null ?
                new ObjectParameter("vNombres", vNombres) :
                new ObjectParameter("vNombres", typeof(string));
    
            var vApePaternoParameter = vApePaterno != null ?
                new ObjectParameter("vApePaterno", vApePaterno) :
                new ObjectParameter("vApePaterno", typeof(string));
    
            var vApeMaternoParameter = vApeMaterno != null ?
                new ObjectParameter("vApeMaterno", vApeMaterno) :
                new ObjectParameter("vApeMaterno", typeof(string));
    
            var vCorreoParameter = vCorreo != null ?
                new ObjectParameter("vCorreo", vCorreo) :
                new ObjectParameter("vCorreo", typeof(string));
    
            var vTel_cliParameter = vTel_cli != null ?
                new ObjectParameter("vTel_cli", vTel_cli) :
                new ObjectParameter("vTel_cli", typeof(string));
    
            var vDir_cliParameter = vDir_cli != null ?
                new ObjectParameter("vDir_cli", vDir_cli) :
                new ObjectParameter("vDir_cli", typeof(string));
    
            var vDni_cliParameter = vDni_cli != null ?
                new ObjectParameter("vDni_cli", vDni_cli) :
                new ObjectParameter("vDni_cli", typeof(string));
    
            var vSexoParameter = vSexo != null ?
                new ObjectParameter("vSexo", vSexo) :
                new ObjectParameter("vSexo", typeof(string));
    
            var vFec_nacParameter = vFec_nac.HasValue ?
                new ObjectParameter("vFec_nac", vFec_nac) :
                new ObjectParameter("vFec_nac", typeof(System.DateTime));
    
            var vEst_cliParameter = vEst_cli.HasValue ?
                new ObjectParameter("vEst_cli", vEst_cli) :
                new ObjectParameter("vEst_cli", typeof(int));
    
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            var vUsu_Ult_ModParameter = vUsu_Ult_Mod != null ?
                new ObjectParameter("vUsu_Ult_Mod", vUsu_Ult_Mod) :
                new ObjectParameter("vUsu_Ult_Mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarCliente", vcodParameter, vNombresParameter, vApePaternoParameter, vApeMaternoParameter, vCorreoParameter, vTel_cliParameter, vDir_cliParameter, vDni_cliParameter, vSexoParameter, vFec_nacParameter, vEst_cliParameter, vId_UbigeoParameter, vUsu_Ult_ModParameter);
        }
    
        public virtual int usp_EliminarCliente(Nullable<int> vcod)
        {
            var vcodParameter = vcod.HasValue ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarCliente", vcodParameter);
        }
    
        public virtual int usp_InsertarCliente(string vNombres, string vApePaterno, string vApeMaterno, string vCorreo, string vTel_cli, string vDir_cli, string vDni_cli, string vSexo, Nullable<System.DateTime> vFec_nac, Nullable<int> vEst_cli, string vId_Ubigeo, string vUsu_Registro)
        {
            var vNombresParameter = vNombres != null ?
                new ObjectParameter("vNombres", vNombres) :
                new ObjectParameter("vNombres", typeof(string));
    
            var vApePaternoParameter = vApePaterno != null ?
                new ObjectParameter("vApePaterno", vApePaterno) :
                new ObjectParameter("vApePaterno", typeof(string));
    
            var vApeMaternoParameter = vApeMaterno != null ?
                new ObjectParameter("vApeMaterno", vApeMaterno) :
                new ObjectParameter("vApeMaterno", typeof(string));
    
            var vCorreoParameter = vCorreo != null ?
                new ObjectParameter("vCorreo", vCorreo) :
                new ObjectParameter("vCorreo", typeof(string));
    
            var vTel_cliParameter = vTel_cli != null ?
                new ObjectParameter("vTel_cli", vTel_cli) :
                new ObjectParameter("vTel_cli", typeof(string));
    
            var vDir_cliParameter = vDir_cli != null ?
                new ObjectParameter("vDir_cli", vDir_cli) :
                new ObjectParameter("vDir_cli", typeof(string));
    
            var vDni_cliParameter = vDni_cli != null ?
                new ObjectParameter("vDni_cli", vDni_cli) :
                new ObjectParameter("vDni_cli", typeof(string));
    
            var vSexoParameter = vSexo != null ?
                new ObjectParameter("vSexo", vSexo) :
                new ObjectParameter("vSexo", typeof(string));
    
            var vFec_nacParameter = vFec_nac.HasValue ?
                new ObjectParameter("vFec_nac", vFec_nac) :
                new ObjectParameter("vFec_nac", typeof(System.DateTime));
    
            var vEst_cliParameter = vEst_cli.HasValue ?
                new ObjectParameter("vEst_cli", vEst_cli) :
                new ObjectParameter("vEst_cli", typeof(int));
    
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            var vUsu_RegistroParameter = vUsu_Registro != null ?
                new ObjectParameter("vUsu_Registro", vUsu_Registro) :
                new ObjectParameter("vUsu_Registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarCliente", vNombresParameter, vApePaternoParameter, vApeMaternoParameter, vCorreoParameter, vTel_cliParameter, vDir_cliParameter, vDni_cliParameter, vSexoParameter, vFec_nacParameter, vEst_cliParameter, vId_UbigeoParameter, vUsu_RegistroParameter);
        }
    
        public virtual ObjectResult<usp_ListarCliente_Result> usp_ListarCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarCliente_Result>("usp_ListarCliente");
        }
    
        public virtual int usp_ActualizarDisciplina(string vCod, string vNombre, string vDuracion, string vIntensidad, Nullable<decimal> vPrecio, Nullable<int> vId_Cat)
        {
            var vCodParameter = vCod != null ?
                new ObjectParameter("vCod", vCod) :
                new ObjectParameter("vCod", typeof(string));
    
            var vNombreParameter = vNombre != null ?
                new ObjectParameter("vNombre", vNombre) :
                new ObjectParameter("vNombre", typeof(string));
    
            var vDuracionParameter = vDuracion != null ?
                new ObjectParameter("vDuracion", vDuracion) :
                new ObjectParameter("vDuracion", typeof(string));
    
            var vIntensidadParameter = vIntensidad != null ?
                new ObjectParameter("vIntensidad", vIntensidad) :
                new ObjectParameter("vIntensidad", typeof(string));
    
            var vPrecioParameter = vPrecio.HasValue ?
                new ObjectParameter("vPrecio", vPrecio) :
                new ObjectParameter("vPrecio", typeof(decimal));
    
            var vId_CatParameter = vId_Cat.HasValue ?
                new ObjectParameter("vId_Cat", vId_Cat) :
                new ObjectParameter("vId_Cat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarDisciplina", vCodParameter, vNombreParameter, vDuracionParameter, vIntensidadParameter, vPrecioParameter, vId_CatParameter);
        }
    
        public virtual int usp_EliminarDisciplina(string vCod)
        {
            var vCodParameter = vCod != null ?
                new ObjectParameter("vCod", vCod) :
                new ObjectParameter("vCod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarDisciplina", vCodParameter);
        }
    
        public virtual int usp_InsertarDisciplina(string vNombre, string vDuracion, string vIntensidad, Nullable<decimal> vPrecio, Nullable<int> vId_Cat)
        {
            var vNombreParameter = vNombre != null ?
                new ObjectParameter("vNombre", vNombre) :
                new ObjectParameter("vNombre", typeof(string));
    
            var vDuracionParameter = vDuracion != null ?
                new ObjectParameter("vDuracion", vDuracion) :
                new ObjectParameter("vDuracion", typeof(string));
    
            var vIntensidadParameter = vIntensidad != null ?
                new ObjectParameter("vIntensidad", vIntensidad) :
                new ObjectParameter("vIntensidad", typeof(string));
    
            var vPrecioParameter = vPrecio.HasValue ?
                new ObjectParameter("vPrecio", vPrecio) :
                new ObjectParameter("vPrecio", typeof(decimal));
    
            var vId_CatParameter = vId_Cat.HasValue ?
                new ObjectParameter("vId_Cat", vId_Cat) :
                new ObjectParameter("vId_Cat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarDisciplina", vNombreParameter, vDuracionParameter, vIntensidadParameter, vPrecioParameter, vId_CatParameter);
        }
    
        public virtual int usp_ActualizarInstructor(string vCod, string vNombre, string vApePaterno, string vApeMaterno, string vCorreo, string vTel_inst, string vDni_inst, string vDir_inst, Nullable<System.DateTime> vFec_nac, string vUbigeo, string vUsu_Ult_Mod, Nullable<int> vEst_ins)
        {
            var vCodParameter = vCod != null ?
                new ObjectParameter("vCod", vCod) :
                new ObjectParameter("vCod", typeof(string));
    
            var vNombreParameter = vNombre != null ?
                new ObjectParameter("vNombre", vNombre) :
                new ObjectParameter("vNombre", typeof(string));
    
            var vApePaternoParameter = vApePaterno != null ?
                new ObjectParameter("vApePaterno", vApePaterno) :
                new ObjectParameter("vApePaterno", typeof(string));
    
            var vApeMaternoParameter = vApeMaterno != null ?
                new ObjectParameter("vApeMaterno", vApeMaterno) :
                new ObjectParameter("vApeMaterno", typeof(string));
    
            var vCorreoParameter = vCorreo != null ?
                new ObjectParameter("vCorreo", vCorreo) :
                new ObjectParameter("vCorreo", typeof(string));
    
            var vTel_instParameter = vTel_inst != null ?
                new ObjectParameter("vTel_inst", vTel_inst) :
                new ObjectParameter("vTel_inst", typeof(string));
    
            var vDni_instParameter = vDni_inst != null ?
                new ObjectParameter("vDni_inst", vDni_inst) :
                new ObjectParameter("vDni_inst", typeof(string));
    
            var vDir_instParameter = vDir_inst != null ?
                new ObjectParameter("vDir_inst", vDir_inst) :
                new ObjectParameter("vDir_inst", typeof(string));
    
            var vFec_nacParameter = vFec_nac.HasValue ?
                new ObjectParameter("vFec_nac", vFec_nac) :
                new ObjectParameter("vFec_nac", typeof(System.DateTime));
    
            var vUbigeoParameter = vUbigeo != null ?
                new ObjectParameter("vUbigeo", vUbigeo) :
                new ObjectParameter("vUbigeo", typeof(string));
    
            var vUsu_Ult_ModParameter = vUsu_Ult_Mod != null ?
                new ObjectParameter("vUsu_Ult_Mod", vUsu_Ult_Mod) :
                new ObjectParameter("vUsu_Ult_Mod", typeof(string));
    
            var vEst_insParameter = vEst_ins.HasValue ?
                new ObjectParameter("vEst_ins", vEst_ins) :
                new ObjectParameter("vEst_ins", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarInstructor", vCodParameter, vNombreParameter, vApePaternoParameter, vApeMaternoParameter, vCorreoParameter, vTel_instParameter, vDni_instParameter, vDir_instParameter, vFec_nacParameter, vUbigeoParameter, vUsu_Ult_ModParameter, vEst_insParameter);
        }
    
        public virtual int usp_EliminarInstructor(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarInstructor", vcodParameter);
        }
    
        public virtual int usp_InsertarInstructor(string vNombre, string vApePaterno, string vApeMaterno, string vCorreo, string vTel_inst, string vDni_inst, string vDir_inst, Nullable<System.DateTime> vFec_nac, string vUbigeo, Nullable<int> vEst_ins, string vUsu_Reg)
        {
            var vNombreParameter = vNombre != null ?
                new ObjectParameter("vNombre", vNombre) :
                new ObjectParameter("vNombre", typeof(string));
    
            var vApePaternoParameter = vApePaterno != null ?
                new ObjectParameter("vApePaterno", vApePaterno) :
                new ObjectParameter("vApePaterno", typeof(string));
    
            var vApeMaternoParameter = vApeMaterno != null ?
                new ObjectParameter("vApeMaterno", vApeMaterno) :
                new ObjectParameter("vApeMaterno", typeof(string));
    
            var vCorreoParameter = vCorreo != null ?
                new ObjectParameter("vCorreo", vCorreo) :
                new ObjectParameter("vCorreo", typeof(string));
    
            var vTel_instParameter = vTel_inst != null ?
                new ObjectParameter("vTel_inst", vTel_inst) :
                new ObjectParameter("vTel_inst", typeof(string));
    
            var vDni_instParameter = vDni_inst != null ?
                new ObjectParameter("vDni_inst", vDni_inst) :
                new ObjectParameter("vDni_inst", typeof(string));
    
            var vDir_instParameter = vDir_inst != null ?
                new ObjectParameter("vDir_inst", vDir_inst) :
                new ObjectParameter("vDir_inst", typeof(string));
    
            var vFec_nacParameter = vFec_nac.HasValue ?
                new ObjectParameter("vFec_nac", vFec_nac) :
                new ObjectParameter("vFec_nac", typeof(System.DateTime));
    
            var vUbigeoParameter = vUbigeo != null ?
                new ObjectParameter("vUbigeo", vUbigeo) :
                new ObjectParameter("vUbigeo", typeof(string));
    
            var vEst_insParameter = vEst_ins.HasValue ?
                new ObjectParameter("vEst_ins", vEst_ins) :
                new ObjectParameter("vEst_ins", typeof(int));
    
            var vUsu_RegParameter = vUsu_Reg != null ?
                new ObjectParameter("vUsu_Reg", vUsu_Reg) :
                new ObjectParameter("vUsu_Reg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarInstructor", vNombreParameter, vApePaternoParameter, vApeMaternoParameter, vCorreoParameter, vTel_instParameter, vDni_instParameter, vDir_instParameter, vFec_nacParameter, vUbigeoParameter, vEst_insParameter, vUsu_RegParameter);
        }
    
        public virtual ObjectResult<usp_Ubigeo_Departamentos_Result> usp_Ubigeo_Departamentos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_Departamentos_Result>("usp_Ubigeo_Departamentos");
        }
    
        public virtual ObjectResult<usp_Ubigeo_DistritosProvinciaDepartamento_Result> usp_Ubigeo_DistritosProvinciaDepartamento(string idDepartamento, string idProvincia)
        {
            var idDepartamentoParameter = idDepartamento != null ?
                new ObjectParameter("IdDepartamento", idDepartamento) :
                new ObjectParameter("IdDepartamento", typeof(string));
    
            var idProvinciaParameter = idProvincia != null ?
                new ObjectParameter("IdProvincia", idProvincia) :
                new ObjectParameter("IdProvincia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_DistritosProvinciaDepartamento_Result>("usp_Ubigeo_DistritosProvinciaDepartamento", idDepartamentoParameter, idProvinciaParameter);
        }
    
        public virtual ObjectResult<usp_Ubigeo_ProvinciasDepartamento_Result> usp_Ubigeo_ProvinciasDepartamento(string idDepartamento)
        {
            var idDepartamentoParameter = idDepartamento != null ?
                new ObjectParameter("IdDepartamento", idDepartamento) :
                new ObjectParameter("IdDepartamento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_ProvinciasDepartamento_Result>("usp_Ubigeo_ProvinciasDepartamento", idDepartamentoParameter);
        }
    
        public virtual int usp_InsertarClaseProgramada(Nullable<int> vsalon, string vIns_disp, Nullable<System.DateTime> vFec_clas, Nullable<System.DateTime> vH_emp, Nullable<System.DateTime> vH_term, Nullable<int> vEst_clase, string vUsu_Reg)
        {
            var vsalonParameter = vsalon.HasValue ?
                new ObjectParameter("vsalon", vsalon) :
                new ObjectParameter("vsalon", typeof(int));
    
            var vIns_dispParameter = vIns_disp != null ?
                new ObjectParameter("vIns_disp", vIns_disp) :
                new ObjectParameter("vIns_disp", typeof(string));
    
            var vFec_clasParameter = vFec_clas.HasValue ?
                new ObjectParameter("vFec_clas", vFec_clas) :
                new ObjectParameter("vFec_clas", typeof(System.DateTime));
    
            var vH_empParameter = vH_emp.HasValue ?
                new ObjectParameter("vH_emp", vH_emp) :
                new ObjectParameter("vH_emp", typeof(System.DateTime));
    
            var vH_termParameter = vH_term.HasValue ?
                new ObjectParameter("vH_term", vH_term) :
                new ObjectParameter("vH_term", typeof(System.DateTime));
    
            var vEst_claseParameter = vEst_clase.HasValue ?
                new ObjectParameter("vEst_clase", vEst_clase) :
                new ObjectParameter("vEst_clase", typeof(int));
    
            var vUsu_RegParameter = vUsu_Reg != null ?
                new ObjectParameter("vUsu_Reg", vUsu_Reg) :
                new ObjectParameter("vUsu_Reg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarClaseProgramada", vsalonParameter, vIns_dispParameter, vFec_clasParameter, vH_empParameter, vH_termParameter, vEst_claseParameter, vUsu_RegParameter);
        }
    
        public virtual ObjectResult<usp_Combo_Instructor_Result> usp_Combo_Instructor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Combo_Instructor_Result>("usp_Combo_Instructor");
        }
    
        public virtual ObjectResult<usp_Combo_InstructorDisciplina_Result> usp_Combo_InstructorDisciplina(string id_Instructor)
        {
            var id_InstructorParameter = id_Instructor != null ?
                new ObjectParameter("Id_Instructor", id_Instructor) :
                new ObjectParameter("Id_Instructor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Combo_InstructorDisciplina_Result>("usp_Combo_InstructorDisciplina", id_InstructorParameter);
        }
    
        public virtual int usp_ActualizarClaseProgramada(Nullable<int> vcod, Nullable<int> vsalon, string vIns_disp, Nullable<System.DateTime> vFec_clase, Nullable<System.TimeSpan> vH_emp, Nullable<System.TimeSpan> vH_term, Nullable<int> vEst_clase, string vUsu_Ult_Mod)
        {
            var vcodParameter = vcod.HasValue ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(int));
    
            var vsalonParameter = vsalon.HasValue ?
                new ObjectParameter("vsalon", vsalon) :
                new ObjectParameter("vsalon", typeof(int));
    
            var vIns_dispParameter = vIns_disp != null ?
                new ObjectParameter("vIns_disp", vIns_disp) :
                new ObjectParameter("vIns_disp", typeof(string));
    
            var vFec_claseParameter = vFec_clase.HasValue ?
                new ObjectParameter("vFec_clase", vFec_clase) :
                new ObjectParameter("vFec_clase", typeof(System.DateTime));
    
            var vH_empParameter = vH_emp.HasValue ?
                new ObjectParameter("vH_emp", vH_emp) :
                new ObjectParameter("vH_emp", typeof(System.TimeSpan));
    
            var vH_termParameter = vH_term.HasValue ?
                new ObjectParameter("vH_term", vH_term) :
                new ObjectParameter("vH_term", typeof(System.TimeSpan));
    
            var vEst_claseParameter = vEst_clase.HasValue ?
                new ObjectParameter("vEst_clase", vEst_clase) :
                new ObjectParameter("vEst_clase", typeof(int));
    
            var vUsu_Ult_ModParameter = vUsu_Ult_Mod != null ?
                new ObjectParameter("vUsu_Ult_Mod", vUsu_Ult_Mod) :
                new ObjectParameter("vUsu_Ult_Mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarClaseProgramada", vcodParameter, vsalonParameter, vIns_dispParameter, vFec_claseParameter, vH_empParameter, vH_termParameter, vEst_claseParameter, vUsu_Ult_ModParameter);
        }
    
        public virtual int usp_ActualizarClaseProgramada_TEST(Nullable<int> vcod, Nullable<int> vsalon, string vIns_disp, Nullable<System.DateTime> vFec_clase, Nullable<System.DateTime> vH_emp, Nullable<System.DateTime> vH_term, Nullable<int> vEst_clase, string vUsu_Ult_Mod)
        {
            var vcodParameter = vcod.HasValue ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(int));
    
            var vsalonParameter = vsalon.HasValue ?
                new ObjectParameter("vsalon", vsalon) :
                new ObjectParameter("vsalon", typeof(int));
    
            var vIns_dispParameter = vIns_disp != null ?
                new ObjectParameter("vIns_disp", vIns_disp) :
                new ObjectParameter("vIns_disp", typeof(string));
    
            var vFec_claseParameter = vFec_clase.HasValue ?
                new ObjectParameter("vFec_clase", vFec_clase) :
                new ObjectParameter("vFec_clase", typeof(System.DateTime));
    
            var vH_empParameter = vH_emp.HasValue ?
                new ObjectParameter("vH_emp", vH_emp) :
                new ObjectParameter("vH_emp", typeof(System.DateTime));
    
            var vH_termParameter = vH_term.HasValue ?
                new ObjectParameter("vH_term", vH_term) :
                new ObjectParameter("vH_term", typeof(System.DateTime));
    
            var vEst_claseParameter = vEst_clase.HasValue ?
                new ObjectParameter("vEst_clase", vEst_clase) :
                new ObjectParameter("vEst_clase", typeof(int));
    
            var vUsu_Ult_ModParameter = vUsu_Ult_Mod != null ?
                new ObjectParameter("vUsu_Ult_Mod", vUsu_Ult_Mod) :
                new ObjectParameter("vUsu_Ult_Mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarClaseProgramada_TEST", vcodParameter, vsalonParameter, vIns_dispParameter, vFec_claseParameter, vH_empParameter, vH_termParameter, vEst_claseParameter, vUsu_Ult_ModParameter);
        }
    
        public virtual int usp_InsertarSalon(string vNombre, string vArea, Nullable<int> vCapacidad, Nullable<int> vEstado, string vDescripcion)
        {
            var vNombreParameter = vNombre != null ?
                new ObjectParameter("vNombre", vNombre) :
                new ObjectParameter("vNombre", typeof(string));
    
            var vAreaParameter = vArea != null ?
                new ObjectParameter("vArea", vArea) :
                new ObjectParameter("vArea", typeof(string));
    
            var vCapacidadParameter = vCapacidad.HasValue ?
                new ObjectParameter("vCapacidad", vCapacidad) :
                new ObjectParameter("vCapacidad", typeof(int));
    
            var vEstadoParameter = vEstado.HasValue ?
                new ObjectParameter("vEstado", vEstado) :
                new ObjectParameter("vEstado", typeof(int));
    
            var vDescripcionParameter = vDescripcion != null ?
                new ObjectParameter("vDescripcion", vDescripcion) :
                new ObjectParameter("vDescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarSalon", vNombreParameter, vAreaParameter, vCapacidadParameter, vEstadoParameter, vDescripcionParameter);
        }
    
        public virtual int usp_ActualizarSalon(Nullable<int> vCod, string vNombre, string vArea, Nullable<int> vCapacidad, Nullable<int> vEstado, string vDescripcion)
        {
            var vCodParameter = vCod.HasValue ?
                new ObjectParameter("vCod", vCod) :
                new ObjectParameter("vCod", typeof(int));
    
            var vNombreParameter = vNombre != null ?
                new ObjectParameter("vNombre", vNombre) :
                new ObjectParameter("vNombre", typeof(string));
    
            var vAreaParameter = vArea != null ?
                new ObjectParameter("vArea", vArea) :
                new ObjectParameter("vArea", typeof(string));
    
            var vCapacidadParameter = vCapacidad.HasValue ?
                new ObjectParameter("vCapacidad", vCapacidad) :
                new ObjectParameter("vCapacidad", typeof(int));
    
            var vEstadoParameter = vEstado.HasValue ?
                new ObjectParameter("vEstado", vEstado) :
                new ObjectParameter("vEstado", typeof(int));
    
            var vDescripcionParameter = vDescripcion != null ?
                new ObjectParameter("vDescripcion", vDescripcion) :
                new ObjectParameter("vDescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarSalon", vCodParameter, vNombreParameter, vAreaParameter, vCapacidadParameter, vEstadoParameter, vDescripcionParameter);
        }
    
        public virtual int usp_ActualizarClienteEstado(Nullable<int> vcod, string vcoment)
        {
            var vcodParameter = vcod.HasValue ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(int));
    
            var vcomentParameter = vcoment != null ?
                new ObjectParameter("vcoment", vcoment) :
                new ObjectParameter("vcoment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarClienteEstado", vcodParameter, vcomentParameter);
        }
    
        public virtual int usp_InsertarCliente_TEST(string vNombres, string vApePaterno, string vApeMaterno, string vCorreo, string vTel_cli, string vDir_cli, string vDni_cli, string vSexo, Nullable<System.DateTime> vFec_nac, Nullable<int> vEst_cli, string vId_Ubigeo, string vUsu_Registro)
        {
            var vNombresParameter = vNombres != null ?
                new ObjectParameter("vNombres", vNombres) :
                new ObjectParameter("vNombres", typeof(string));
    
            var vApePaternoParameter = vApePaterno != null ?
                new ObjectParameter("vApePaterno", vApePaterno) :
                new ObjectParameter("vApePaterno", typeof(string));
    
            var vApeMaternoParameter = vApeMaterno != null ?
                new ObjectParameter("vApeMaterno", vApeMaterno) :
                new ObjectParameter("vApeMaterno", typeof(string));
    
            var vCorreoParameter = vCorreo != null ?
                new ObjectParameter("vCorreo", vCorreo) :
                new ObjectParameter("vCorreo", typeof(string));
    
            var vTel_cliParameter = vTel_cli != null ?
                new ObjectParameter("vTel_cli", vTel_cli) :
                new ObjectParameter("vTel_cli", typeof(string));
    
            var vDir_cliParameter = vDir_cli != null ?
                new ObjectParameter("vDir_cli", vDir_cli) :
                new ObjectParameter("vDir_cli", typeof(string));
    
            var vDni_cliParameter = vDni_cli != null ?
                new ObjectParameter("vDni_cli", vDni_cli) :
                new ObjectParameter("vDni_cli", typeof(string));
    
            var vSexoParameter = vSexo != null ?
                new ObjectParameter("vSexo", vSexo) :
                new ObjectParameter("vSexo", typeof(string));
    
            var vFec_nacParameter = vFec_nac.HasValue ?
                new ObjectParameter("vFec_nac", vFec_nac) :
                new ObjectParameter("vFec_nac", typeof(System.DateTime));
    
            var vEst_cliParameter = vEst_cli.HasValue ?
                new ObjectParameter("vEst_cli", vEst_cli) :
                new ObjectParameter("vEst_cli", typeof(int));
    
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            var vUsu_RegistroParameter = vUsu_Registro != null ?
                new ObjectParameter("vUsu_Registro", vUsu_Registro) :
                new ObjectParameter("vUsu_Registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarCliente_TEST", vNombresParameter, vApePaternoParameter, vApeMaternoParameter, vCorreoParameter, vTel_cliParameter, vDir_cliParameter, vDni_cliParameter, vSexoParameter, vFec_nacParameter, vEst_cliParameter, vId_UbigeoParameter, vUsu_RegistroParameter);
        }
    
        public virtual int usp_ActualizarInstructorEstado(string vcod, string vcoment)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            var vcomentParameter = vcoment != null ?
                new ObjectParameter("vcoment", vcoment) :
                new ObjectParameter("vcoment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarInstructorEstado", vcodParameter, vcomentParameter);
        }
    }
}
