//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ReservaYoga
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Administrador
    {
        public int Id_Admin { get; set; }
        public string Nom_Admin { get; set; }
        public string Ape_Admin { get; set; }
        public string Dni_Admin { get; set; }
        public string Correo_Admin { get; set; }
        public Nullable<System.DateTime> Fec_Reg { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
