//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ReservaYoga
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Clase_Programada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Clase_Programada()
        {
            this.Tb_Reserva = new HashSet<Tb_Reserva>();
        }
    
        public int Id_Clase_Prog { get; set; }
        public Nullable<int> Id_Salon { get; set; }
        public string Id_Inst_Disp { get; set; }
        public System.DateTime Fec_Clase { get; set; }
        public Nullable<System.DateTime> Hora_Emp { get; set; }
        public Nullable<System.DateTime> Hora_Term { get; set; }
        public Nullable<int> Est_clase { get; set; }
        public Nullable<System.DateTime> Fec_reg { get; set; }
        public string Usu_reg { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
    
        public virtual Tb_Instructor_Disciplina Tb_Instructor_Disciplina { get; set; }
        public virtual Tb_Salon Tb_Salon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Reserva> Tb_Reserva { get; set; }
    }
}
