//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ReservaYoga
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Instructor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Instructor()
        {
            this.Tb_Instructor_Disciplina = new HashSet<Tb_Instructor_Disciplina>();
        }
    
        public string Id_Instructor { get; set; }
        public string Nombre { get; set; }
        public string ApePaterno { get; set; }
        public string ApeMaterno { get; set; }
        public string Correo { get; set; }
        public string Tel_inst { get; set; }
        public string Dni_inst { get; set; }
        public string Dir_inst { get; set; }
        public Nullable<System.DateTime> Fec_nac { get; set; }
        public string Id_Ubigeo { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<int> Est_ins { get; set; }
        public Nullable<System.DateTime> Fec_reg { get; set; }
        public string Usu_reg { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Instructor_Disciplina> Tb_Instructor_Disciplina { get; set; }
        public virtual Tb_Ubigeo Tb_Ubigeo { get; set; }
    }
}
