//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ReservaYoga
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Instructor_Disciplina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Instructor_Disciplina()
        {
            this.Tb_Clase_Programada = new HashSet<Tb_Clase_Programada>();
        }
    
        public string Id_Inst_Disp { get; set; }
        public string Id_Instructor { get; set; }
        public string Cod_disp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Clase_Programada> Tb_Clase_Programada { get; set; }
        public virtual Tb_Disciplina Tb_Disciplina { get; set; }
        public virtual Tb_Instructor Tb_Instructor { get; set; }
    }
}
