//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ReservaYoga
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Reserva()
        {
            this.Tb_Clase_Programada = new HashSet<Tb_Clase_Programada>();
        }
    
        public Nullable<int> Id_Cliente { get; set; }
        public Nullable<int> Est_resv { get; set; }
        public Nullable<System.DateTime> Fec_resv { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> Fec_reg { get; set; }
        public string Usu_reg { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Cod_resv { get; set; }
    
        public virtual Tb_Cliente Tb_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Clase_Programada> Tb_Clase_Programada { get; set; }
    }
}
