//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ReservaYoga
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Usuario
    {
        public string Pass_Usuario { get; set; }
        public Nullable<int> Est_Usuario { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Registro { get; set; }
        public string Login_Usuario_Correo { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public Nullable<int> Id_Rol { get; set; }
    
        public virtual Tb_Rol Tb_Rol { get; set; }
    }
}
