//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_ConsultaInstructor.ProxyInstructor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstructorDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ReservaYoga")]
    [System.SerializableAttribute()]
    public partial class InstructorDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApePaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dir_instField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dni_instField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Est_insField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoInstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_nacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_regField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_InstructorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tel_instField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_regField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeMaterno {
            get {
                return this.ApeMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeMaternoField, value) != true)) {
                    this.ApeMaternoField = value;
                    this.RaisePropertyChanged("ApeMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePaterno {
            get {
                return this.ApePaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApePaternoField, value) != true)) {
                    this.ApePaternoField = value;
                    this.RaisePropertyChanged("ApePaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dir_inst {
            get {
                return this.Dir_instField;
            }
            set {
                if ((object.ReferenceEquals(this.Dir_instField, value) != true)) {
                    this.Dir_instField = value;
                    this.RaisePropertyChanged("Dir_inst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_inst {
            get {
                return this.Dni_instField;
            }
            set {
                if ((object.ReferenceEquals(this.Dni_instField, value) != true)) {
                    this.Dni_instField = value;
                    this.RaisePropertyChanged("Dni_inst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_ins {
            get {
                return this.Est_insField;
            }
            set {
                if ((this.Est_insField.Equals(value) != true)) {
                    this.Est_insField = value;
                    this.RaisePropertyChanged("Est_ins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoInst {
            get {
                return this.EstadoInstField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoInstField, value) != true)) {
                    this.EstadoInstField = value;
                    this.RaisePropertyChanged("EstadoInst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_nac {
            get {
                return this.Fec_nacField;
            }
            set {
                if ((this.Fec_nacField.Equals(value) != true)) {
                    this.Fec_nacField = value;
                    this.RaisePropertyChanged("Fec_nac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_reg {
            get {
                return this.Fec_regField;
            }
            set {
                if ((this.Fec_regField.Equals(value) != true)) {
                    this.Fec_regField = value;
                    this.RaisePropertyChanged("Fec_reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Instructor {
            get {
                return this.Id_InstructorField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_InstructorField, value) != true)) {
                    this.Id_InstructorField = value;
                    this.RaisePropertyChanged("Id_Instructor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubigeo {
            get {
                return this.Id_UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_UbigeoField, value) != true)) {
                    this.Id_UbigeoField = value;
                    this.RaisePropertyChanged("Id_Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_inst {
            get {
                return this.Tel_instField;
            }
            set {
                if ((object.ReferenceEquals(this.Tel_instField, value) != true)) {
                    this.Tel_instField = value;
                    this.RaisePropertyChanged("Tel_inst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_reg {
            get {
                return this.Usu_regField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_regField, value) != true)) {
                    this.Usu_regField = value;
                    this.RaisePropertyChanged("Usu_reg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyInstructor.IServicioInstructor")]
    public interface IServicioInstructor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/InsertarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/InsertarInstructorResponse")]
        bool InsertarInstructor(WEB_ConsultaInstructor.ProxyInstructor.InstructorDC objInstructorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/InsertarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/InsertarInstructorResponse")]
        System.Threading.Tasks.Task<bool> InsertarInstructorAsync(WEB_ConsultaInstructor.ProxyInstructor.InstructorDC objInstructorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/ActualizarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/ActualizarInstructorResponse")]
        bool ActualizarInstructor(WEB_ConsultaInstructor.ProxyInstructor.InstructorDC objInstructorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/ActualizarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/ActualizarInstructorResponse")]
        System.Threading.Tasks.Task<bool> ActualizarInstructorAsync(WEB_ConsultaInstructor.ProxyInstructor.InstructorDC objInstructorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/EliminarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/EliminarInstructorResponse")]
        bool EliminarInstructor(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/EliminarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/EliminarInstructorResponse")]
        System.Threading.Tasks.Task<bool> EliminarInstructorAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/ConsultarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/ConsultarInstructorResponse")]
        WEB_ConsultaInstructor.ProxyInstructor.InstructorDC ConsultarInstructor(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/ConsultarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/ConsultarInstructorResponse")]
        System.Threading.Tasks.Task<WEB_ConsultaInstructor.ProxyInstructor.InstructorDC> ConsultarInstructorAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/ListarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/ListarInstructorResponse")]
        WEB_ConsultaInstructor.ProxyInstructor.InstructorDC[] ListarInstructor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/ListarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/ListarInstructorResponse")]
        System.Threading.Tasks.Task<WEB_ConsultaInstructor.ProxyInstructor.InstructorDC[]> ListarInstructorAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioInstructorChannel : WEB_ConsultaInstructor.ProxyInstructor.IServicioInstructor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioInstructorClient : System.ServiceModel.ClientBase<WEB_ConsultaInstructor.ProxyInstructor.IServicioInstructor>, WEB_ConsultaInstructor.ProxyInstructor.IServicioInstructor {
        
        public ServicioInstructorClient() {
        }
        
        public ServicioInstructorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioInstructorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioInstructorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioInstructorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertarInstructor(WEB_ConsultaInstructor.ProxyInstructor.InstructorDC objInstructorDC) {
            return base.Channel.InsertarInstructor(objInstructorDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarInstructorAsync(WEB_ConsultaInstructor.ProxyInstructor.InstructorDC objInstructorDC) {
            return base.Channel.InsertarInstructorAsync(objInstructorDC);
        }
        
        public bool ActualizarInstructor(WEB_ConsultaInstructor.ProxyInstructor.InstructorDC objInstructorDC) {
            return base.Channel.ActualizarInstructor(objInstructorDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarInstructorAsync(WEB_ConsultaInstructor.ProxyInstructor.InstructorDC objInstructorDC) {
            return base.Channel.ActualizarInstructorAsync(objInstructorDC);
        }
        
        public bool EliminarInstructor(string strCodigo) {
            return base.Channel.EliminarInstructor(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarInstructorAsync(string strCodigo) {
            return base.Channel.EliminarInstructorAsync(strCodigo);
        }
        
        public WEB_ConsultaInstructor.ProxyInstructor.InstructorDC ConsultarInstructor(string strCodigo) {
            return base.Channel.ConsultarInstructor(strCodigo);
        }
        
        public System.Threading.Tasks.Task<WEB_ConsultaInstructor.ProxyInstructor.InstructorDC> ConsultarInstructorAsync(string strCodigo) {
            return base.Channel.ConsultarInstructorAsync(strCodigo);
        }
        
        public WEB_ConsultaInstructor.ProxyInstructor.InstructorDC[] ListarInstructor() {
            return base.Channel.ListarInstructor();
        }
        
        public System.Threading.Tasks.Task<WEB_ConsultaInstructor.ProxyInstructor.InstructorDC[]> ListarInstructorAsync() {
            return base.Channel.ListarInstructorAsync();
        }
    }
}
