//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxySalon
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalonDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ReservaYoga")]
    public partial class SalonDC : object
    {
        
        private string AreaField;
        
        private short CapacidadField;
        
        private string DescripcionField;
        
        private short EstadoField;
        
        private string EstadoTextoField;
        
        private short Id_SalonField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area
        {
            get
            {
                return this.AreaField;
            }
            set
            {
                this.AreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Capacidad
        {
            get
            {
                return this.CapacidadField;
            }
            set
            {
                this.CapacidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoTexto
        {
            get
            {
                return this.EstadoTextoField;
            }
            set
            {
                this.EstadoTextoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Salon
        {
            get
            {
                return this.Id_SalonField;
            }
            set
            {
                this.Id_SalonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxySalon.IServicioSalon")]
    public interface IServicioSalon
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSalon/ListarSalon", ReplyAction="http://tempuri.org/IServicioSalon/ListarSalonResponse")]
        System.Collections.Generic.List<ProxySalon.SalonDC> ListarSalon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSalon/ListarSalon", ReplyAction="http://tempuri.org/IServicioSalon/ListarSalonResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxySalon.SalonDC>> ListarSalonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSalon/ListarSalon_Grid", ReplyAction="http://tempuri.org/IServicioSalon/ListarSalon_GridResponse")]
        System.Collections.Generic.List<ProxySalon.SalonDC> ListarSalon_Grid();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSalon/ListarSalon_Grid", ReplyAction="http://tempuri.org/IServicioSalon/ListarSalon_GridResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxySalon.SalonDC>> ListarSalon_GridAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSalon/InsertarSalon", ReplyAction="http://tempuri.org/IServicioSalon/InsertarSalonResponse")]
        bool InsertarSalon(ProxySalon.SalonDC objSalonDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSalon/InsertarSalon", ReplyAction="http://tempuri.org/IServicioSalon/InsertarSalonResponse")]
        System.Threading.Tasks.Task<bool> InsertarSalonAsync(ProxySalon.SalonDC objSalonDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSalon/ActualizarSalon", ReplyAction="http://tempuri.org/IServicioSalon/ActualizarSalonResponse")]
        bool ActualizarSalon(ProxySalon.SalonDC objSalonDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSalon/ActualizarSalon", ReplyAction="http://tempuri.org/IServicioSalon/ActualizarSalonResponse")]
        System.Threading.Tasks.Task<bool> ActualizarSalonAsync(ProxySalon.SalonDC objSalonDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSalon/ConsultarSalon", ReplyAction="http://tempuri.org/IServicioSalon/ConsultarSalonResponse")]
        ProxySalon.SalonDC ConsultarSalon(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSalon/ConsultarSalon", ReplyAction="http://tempuri.org/IServicioSalon/ConsultarSalonResponse")]
        System.Threading.Tasks.Task<ProxySalon.SalonDC> ConsultarSalonAsync(short strId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioSalonChannel : ProxySalon.IServicioSalon, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioSalonClient : System.ServiceModel.ClientBase<ProxySalon.IServicioSalon>, ProxySalon.IServicioSalon
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioSalonClient() : 
                base(ServicioSalonClient.GetDefaultBinding(), ServicioSalonClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioSalon.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioSalonClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioSalonClient.GetBindingForEndpoint(endpointConfiguration), ServicioSalonClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioSalonClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioSalonClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioSalonClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioSalonClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioSalonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxySalon.SalonDC> ListarSalon()
        {
            return base.Channel.ListarSalon();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxySalon.SalonDC>> ListarSalonAsync()
        {
            return base.Channel.ListarSalonAsync();
        }
        
        public System.Collections.Generic.List<ProxySalon.SalonDC> ListarSalon_Grid()
        {
            return base.Channel.ListarSalon_Grid();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxySalon.SalonDC>> ListarSalon_GridAsync()
        {
            return base.Channel.ListarSalon_GridAsync();
        }
        
        public bool InsertarSalon(ProxySalon.SalonDC objSalonDC)
        {
            return base.Channel.InsertarSalon(objSalonDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarSalonAsync(ProxySalon.SalonDC objSalonDC)
        {
            return base.Channel.InsertarSalonAsync(objSalonDC);
        }
        
        public bool ActualizarSalon(ProxySalon.SalonDC objSalonDC)
        {
            return base.Channel.ActualizarSalon(objSalonDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarSalonAsync(ProxySalon.SalonDC objSalonDC)
        {
            return base.Channel.ActualizarSalonAsync(objSalonDC);
        }
        
        public ProxySalon.SalonDC ConsultarSalon(short strId)
        {
            return base.Channel.ConsultarSalon(strId);
        }
        
        public System.Threading.Tasks.Task<ProxySalon.SalonDC> ConsultarSalonAsync(short strId)
        {
            return base.Channel.ConsultarSalonAsync(strId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioSalon))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioSalon))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ReservaYoga/ServicioSalon/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioSalonClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioSalon);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioSalonClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioSalon);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioSalon,
        }
    }
}
