//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyCliente
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ReservaYoga")]
    public partial class ClienteDC : object
    {
        
        private string ApeMaternoField;
        
        private string ApePaternoField;
        
        private string ComentarioField;
        
        private string CorreoField;
        
        private string DepartamentoField;
        
        private string Dir_cliField;
        
        private string DistritoField;
        
        private string Dni_cliField;
        
        private short Est_cliField;
        
        private string EstadoTextoField;
        
        private System.DateTime Fec_Ult_ModField;
        
        private System.DateTime Fec_nacField;
        
        private System.DateTime Fec_regField;
        
        private string FotoField;
        
        private short Id_ClienteField;
        
        private string Id_UbigeoField;
        
        private string NombresField;
        
        private string ProvinciaField;
        
        private string SexoField;
        
        private string SexoTextoField;
        
        private string Tel_cliField;
        
        private string Usu_Ult_ModField;
        
        private string Usu_regField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeMaterno
        {
            get
            {
                return this.ApeMaternoField;
            }
            set
            {
                this.ApeMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePaterno
        {
            get
            {
                return this.ApePaternoField;
            }
            set
            {
                this.ApePaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comentario
        {
            get
            {
                return this.ComentarioField;
            }
            set
            {
                this.ComentarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dir_cli
        {
            get
            {
                return this.Dir_cliField;
            }
            set
            {
                this.Dir_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                this.DistritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_cli
        {
            get
            {
                return this.Dni_cliField;
            }
            set
            {
                this.Dni_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_cli
        {
            get
            {
                return this.Est_cliField;
            }
            set
            {
                this.Est_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoTexto
        {
            get
            {
                return this.EstadoTextoField;
            }
            set
            {
                this.EstadoTextoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod
        {
            get
            {
                return this.Fec_Ult_ModField;
            }
            set
            {
                this.Fec_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_nac
        {
            get
            {
                return this.Fec_nacField;
            }
            set
            {
                this.Fec_nacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_reg
        {
            get
            {
                return this.Fec_regField;
            }
            set
            {
                this.Fec_regField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foto
        {
            get
            {
                return this.FotoField;
            }
            set
            {
                this.FotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Cliente
        {
            get
            {
                return this.Id_ClienteField;
            }
            set
            {
                this.Id_ClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubigeo
        {
            get
            {
                return this.Id_UbigeoField;
            }
            set
            {
                this.Id_UbigeoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SexoTexto
        {
            get
            {
                return this.SexoTextoField;
            }
            set
            {
                this.SexoTextoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_cli
        {
            get
            {
                return this.Tel_cliField;
            }
            set
            {
                this.Tel_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod
        {
            get
            {
                return this.Usu_Ult_ModField;
            }
            set
            {
                this.Usu_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_reg
        {
            get
            {
                return this.Usu_regField;
            }
            set
            {
                this.Usu_regField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCliente.IServicioCliente")]
    public interface IServicioCliente
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        bool InsertarCliente(ProxyCliente.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        System.Threading.Tasks.Task<bool> InsertarClienteAsync(ProxyCliente.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        bool ActualizarCliente(ProxyCliente.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        System.Threading.Tasks.Task<bool> ActualizarClienteAsync(ProxyCliente.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EliminarCliente", ReplyAction="http://tempuri.org/IServicioCliente/EliminarClienteResponse")]
        bool EliminarCliente(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EliminarCliente", ReplyAction="http://tempuri.org/IServicioCliente/EliminarClienteResponse")]
        System.Threading.Tasks.Task<bool> EliminarClienteAsync(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        ProxyCliente.ClienteDC ConsultarCliente(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        System.Threading.Tasks.Task<ProxyCliente.ClienteDC> ConsultarClienteAsync(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteResponse")]
        System.Collections.Generic.List<ProxyCliente.ClienteDC> ListarCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCliente.ClienteDC>> ListarClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/UpdateClienteEstado", ReplyAction="http://tempuri.org/IServicioCliente/UpdateClienteEstadoResponse")]
        bool UpdateClienteEstado(ProxyCliente.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/UpdateClienteEstado", ReplyAction="http://tempuri.org/IServicioCliente/UpdateClienteEstadoResponse")]
        System.Threading.Tasks.Task<bool> UpdateClienteEstadoAsync(ProxyCliente.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarClienteEstado", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteEstadoResponse")]
        System.Collections.Generic.List<ProxyCliente.ClienteDC> ListarClienteEstado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarClienteEstado", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteEstadoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCliente.ClienteDC>> ListarClienteEstadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultaClienteDNI", ReplyAction="http://tempuri.org/IServicioCliente/ConsultaClienteDNIResponse")]
        ProxyCliente.ClienteDC ConsultaClienteDNI(string strDni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultaClienteDNI", ReplyAction="http://tempuri.org/IServicioCliente/ConsultaClienteDNIResponse")]
        System.Threading.Tasks.Task<ProxyCliente.ClienteDC> ConsultaClienteDNIAsync(string strDni);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioClienteChannel : ProxyCliente.IServicioCliente, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioClienteClient : System.ServiceModel.ClientBase<ProxyCliente.IServicioCliente>, ProxyCliente.IServicioCliente
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioClienteClient() : 
                base(ServicioClienteClient.GetDefaultBinding(), ServicioClienteClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioCliente.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClienteClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioClienteClient.GetBindingForEndpoint(endpointConfiguration), ServicioClienteClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClienteClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioClienteClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClienteClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioClienteClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool InsertarCliente(ProxyCliente.ClienteDC objClienteDC)
        {
            return base.Channel.InsertarCliente(objClienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarClienteAsync(ProxyCliente.ClienteDC objClienteDC)
        {
            return base.Channel.InsertarClienteAsync(objClienteDC);
        }
        
        public bool ActualizarCliente(ProxyCliente.ClienteDC objClienteDC)
        {
            return base.Channel.ActualizarCliente(objClienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarClienteAsync(ProxyCliente.ClienteDC objClienteDC)
        {
            return base.Channel.ActualizarClienteAsync(objClienteDC);
        }
        
        public bool EliminarCliente(short strId)
        {
            return base.Channel.EliminarCliente(strId);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarClienteAsync(short strId)
        {
            return base.Channel.EliminarClienteAsync(strId);
        }
        
        public ProxyCliente.ClienteDC ConsultarCliente(short strId)
        {
            return base.Channel.ConsultarCliente(strId);
        }
        
        public System.Threading.Tasks.Task<ProxyCliente.ClienteDC> ConsultarClienteAsync(short strId)
        {
            return base.Channel.ConsultarClienteAsync(strId);
        }
        
        public System.Collections.Generic.List<ProxyCliente.ClienteDC> ListarCliente()
        {
            return base.Channel.ListarCliente();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCliente.ClienteDC>> ListarClienteAsync()
        {
            return base.Channel.ListarClienteAsync();
        }
        
        public bool UpdateClienteEstado(ProxyCliente.ClienteDC objClienteDC)
        {
            return base.Channel.UpdateClienteEstado(objClienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateClienteEstadoAsync(ProxyCliente.ClienteDC objClienteDC)
        {
            return base.Channel.UpdateClienteEstadoAsync(objClienteDC);
        }
        
        public System.Collections.Generic.List<ProxyCliente.ClienteDC> ListarClienteEstado()
        {
            return base.Channel.ListarClienteEstado();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCliente.ClienteDC>> ListarClienteEstadoAsync()
        {
            return base.Channel.ListarClienteEstadoAsync();
        }
        
        public ProxyCliente.ClienteDC ConsultaClienteDNI(string strDni)
        {
            return base.Channel.ConsultaClienteDNI(strDni);
        }
        
        public System.Threading.Tasks.Task<ProxyCliente.ClienteDC> ConsultaClienteDNIAsync(string strDni)
        {
            return base.Channel.ConsultaClienteDNIAsync(strDni);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCliente))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCliente))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ReservaYoga/ServicioCliente/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioClienteClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioCliente);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioClienteClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioCliente);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioCliente,
        }
    }
}
