//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyConsulta
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ReservaYoga")]
    public partial class ConsultaDC : object
    {
        
        private string Cod_dispField;
        
        private string DuracionField;
        
        private short Est_claseField;
        
        private string EstadoClaseField;
        
        private System.DateTime Fec_ClaseField;
        
        private System.DateTime Hora_EmpField;
        
        private System.DateTime Hora_TermField;
        
        private short Id_Clase_ProgField;
        
        private string Id_Inst_DispField;
        
        private short Id_SalonField;
        
        private string IntensidadField;
        
        private string NombreDisciplinaField;
        
        private string NombreSalonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_disp
        {
            get
            {
                return this.Cod_dispField;
            }
            set
            {
                this.Cod_dispField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Duracion
        {
            get
            {
                return this.DuracionField;
            }
            set
            {
                this.DuracionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_clase
        {
            get
            {
                return this.Est_claseField;
            }
            set
            {
                this.Est_claseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoClase
        {
            get
            {
                return this.EstadoClaseField;
            }
            set
            {
                this.EstadoClaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Clase
        {
            get
            {
                return this.Fec_ClaseField;
            }
            set
            {
                this.Fec_ClaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Hora_Emp
        {
            get
            {
                return this.Hora_EmpField;
            }
            set
            {
                this.Hora_EmpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Hora_Term
        {
            get
            {
                return this.Hora_TermField;
            }
            set
            {
                this.Hora_TermField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Clase_Prog
        {
            get
            {
                return this.Id_Clase_ProgField;
            }
            set
            {
                this.Id_Clase_ProgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Inst_Disp
        {
            get
            {
                return this.Id_Inst_DispField;
            }
            set
            {
                this.Id_Inst_DispField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Salon
        {
            get
            {
                return this.Id_SalonField;
            }
            set
            {
                this.Id_SalonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Intensidad
        {
            get
            {
                return this.IntensidadField;
            }
            set
            {
                this.IntensidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDisciplina
        {
            get
            {
                return this.NombreDisciplinaField;
            }
            set
            {
                this.NombreDisciplinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreSalon
        {
            get
            {
                return this.NombreSalonField;
            }
            set
            {
                this.NombreSalonField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyConsulta.IConsultaInstructorClases")]
    public interface IConsultaInstructorClases
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaInstructorClases/ListarClasesProgramadasInstructor", ReplyAction="http://tempuri.org/IConsultaInstructorClases/ListarClasesProgramadasInstructorRes" +
            "ponse")]
        System.Collections.Generic.List<ProxyConsulta.ConsultaDC> ListarClasesProgramadasInstructor(string strCodigo, System.DateTime fecIni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaInstructorClases/ListarClasesProgramadasInstructor", ReplyAction="http://tempuri.org/IConsultaInstructorClases/ListarClasesProgramadasInstructorRes" +
            "ponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyConsulta.ConsultaDC>> ListarClasesProgramadasInstructorAsync(string strCodigo, System.DateTime fecIni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaInstructorClases/ListarClasesEntreFechas", ReplyAction="http://tempuri.org/IConsultaInstructorClases/ListarClasesEntreFechasResponse")]
        System.Collections.Generic.List<ProxyConsulta.ConsultaDC> ListarClasesEntreFechas(string strCodigo, System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaInstructorClases/ListarClasesEntreFechas", ReplyAction="http://tempuri.org/IConsultaInstructorClases/ListarClasesEntreFechasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyConsulta.ConsultaDC>> ListarClasesEntreFechasAsync(string strCodigo, System.DateTime fecIni, System.DateTime fecFin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IConsultaInstructorClasesChannel : ProxyConsulta.IConsultaInstructorClases, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ConsultaInstructorClasesClient : System.ServiceModel.ClientBase<ProxyConsulta.IConsultaInstructorClases>, ProxyConsulta.IConsultaInstructorClases
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ConsultaInstructorClasesClient() : 
                base(ConsultaInstructorClasesClient.GetDefaultBinding(), ConsultaInstructorClasesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IConsultaInstructorClases.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultaInstructorClasesClient(EndpointConfiguration endpointConfiguration) : 
                base(ConsultaInstructorClasesClient.GetBindingForEndpoint(endpointConfiguration), ConsultaInstructorClasesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultaInstructorClasesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ConsultaInstructorClasesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultaInstructorClasesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ConsultaInstructorClasesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultaInstructorClasesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyConsulta.ConsultaDC> ListarClasesProgramadasInstructor(string strCodigo, System.DateTime fecIni)
        {
            return base.Channel.ListarClasesProgramadasInstructor(strCodigo, fecIni);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyConsulta.ConsultaDC>> ListarClasesProgramadasInstructorAsync(string strCodigo, System.DateTime fecIni)
        {
            return base.Channel.ListarClasesProgramadasInstructorAsync(strCodigo, fecIni);
        }
        
        public System.Collections.Generic.List<ProxyConsulta.ConsultaDC> ListarClasesEntreFechas(string strCodigo, System.DateTime fecIni, System.DateTime fecFin)
        {
            return base.Channel.ListarClasesEntreFechas(strCodigo, fecIni, fecFin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyConsulta.ConsultaDC>> ListarClasesEntreFechasAsync(string strCodigo, System.DateTime fecIni, System.DateTime fecFin)
        {
            return base.Channel.ListarClasesEntreFechasAsync(strCodigo, fecIni, fecFin);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConsultaInstructorClases))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConsultaInstructorClases))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ReservaYoga/ConsultaInstructorCla" +
                        "ses/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ConsultaInstructorClasesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IConsultaInstructorClases);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ConsultaInstructorClasesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IConsultaInstructorClases);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IConsultaInstructorClases,
        }
    }
}
