//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyClaseProgramada
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaseProgramadaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ReservaYoga")]
    public partial class ClaseProgramadaDC : object
    {
        
        private string ApellidoMInstructorField;
        
        private string ApellidoPInstructorField;
        
        private short CapacidadField;
        
        private string DuracionField;
        
        private short Est_claseField;
        
        private string EstadoField;
        
        private System.DateTime Fec_ClaseField;
        
        private System.DateTime Fec_Ult_ModField;
        
        private System.DateTime Fec_regField;
        
        private System.DateTime Hora_EmpField;
        
        private System.DateTime Hora_TermField;
        
        private short Id_Clase_ProgField;
        
        private string Id_Inst_DispField;
        
        private string Id_InstructorField;
        
        private short Id_SalonField;
        
        private string IntensidadField;
        
        private string NombreField;
        
        private string NombreDisciplinaField;
        
        private string NombreInstructorField;
        
        private string NombreSalonField;
        
        private string Usu_Ult_ModField;
        
        private string Usu_regField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMInstructor
        {
            get
            {
                return this.ApellidoMInstructorField;
            }
            set
            {
                this.ApellidoMInstructorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPInstructor
        {
            get
            {
                return this.ApellidoPInstructorField;
            }
            set
            {
                this.ApellidoPInstructorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Capacidad
        {
            get
            {
                return this.CapacidadField;
            }
            set
            {
                this.CapacidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Duracion
        {
            get
            {
                return this.DuracionField;
            }
            set
            {
                this.DuracionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_clase
        {
            get
            {
                return this.Est_claseField;
            }
            set
            {
                this.Est_claseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Clase
        {
            get
            {
                return this.Fec_ClaseField;
            }
            set
            {
                this.Fec_ClaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod
        {
            get
            {
                return this.Fec_Ult_ModField;
            }
            set
            {
                this.Fec_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_reg
        {
            get
            {
                return this.Fec_regField;
            }
            set
            {
                this.Fec_regField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Hora_Emp
        {
            get
            {
                return this.Hora_EmpField;
            }
            set
            {
                this.Hora_EmpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Hora_Term
        {
            get
            {
                return this.Hora_TermField;
            }
            set
            {
                this.Hora_TermField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Clase_Prog
        {
            get
            {
                return this.Id_Clase_ProgField;
            }
            set
            {
                this.Id_Clase_ProgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Inst_Disp
        {
            get
            {
                return this.Id_Inst_DispField;
            }
            set
            {
                this.Id_Inst_DispField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Instructor
        {
            get
            {
                return this.Id_InstructorField;
            }
            set
            {
                this.Id_InstructorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Salon
        {
            get
            {
                return this.Id_SalonField;
            }
            set
            {
                this.Id_SalonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Intensidad
        {
            get
            {
                return this.IntensidadField;
            }
            set
            {
                this.IntensidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDisciplina
        {
            get
            {
                return this.NombreDisciplinaField;
            }
            set
            {
                this.NombreDisciplinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreInstructor
        {
            get
            {
                return this.NombreInstructorField;
            }
            set
            {
                this.NombreInstructorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreSalon
        {
            get
            {
                return this.NombreSalonField;
            }
            set
            {
                this.NombreSalonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod
        {
            get
            {
                return this.Usu_Ult_ModField;
            }
            set
            {
                this.Usu_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_reg
        {
            get
            {
                return this.Usu_regField;
            }
            set
            {
                this.Usu_regField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyClaseProgramada.IServicioClaseProgramada")]
    public interface IServicioClaseProgramada
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClaseProgramada/ListarClaseProgramada", ReplyAction="http://tempuri.org/IServicioClaseProgramada/ListarClaseProgramadaResponse")]
        System.Collections.Generic.List<ProxyClaseProgramada.ClaseProgramadaDC> ListarClaseProgramada();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClaseProgramada/ListarClaseProgramada", ReplyAction="http://tempuri.org/IServicioClaseProgramada/ListarClaseProgramadaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyClaseProgramada.ClaseProgramadaDC>> ListarClaseProgramadaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClaseProgramada/InsertarClaseProgramada", ReplyAction="http://tempuri.org/IServicioClaseProgramada/InsertarClaseProgramadaResponse")]
        bool InsertarClaseProgramada(ProxyClaseProgramada.ClaseProgramadaDC objClaseProgramadaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClaseProgramada/InsertarClaseProgramada", ReplyAction="http://tempuri.org/IServicioClaseProgramada/InsertarClaseProgramadaResponse")]
        System.Threading.Tasks.Task<bool> InsertarClaseProgramadaAsync(ProxyClaseProgramada.ClaseProgramadaDC objClaseProgramadaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClaseProgramada/ActualizarClaseProgramada", ReplyAction="http://tempuri.org/IServicioClaseProgramada/ActualizarClaseProgramadaResponse")]
        bool ActualizarClaseProgramada(ProxyClaseProgramada.ClaseProgramadaDC objClaseProgramadaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClaseProgramada/ActualizarClaseProgramada", ReplyAction="http://tempuri.org/IServicioClaseProgramada/ActualizarClaseProgramadaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarClaseProgramadaAsync(ProxyClaseProgramada.ClaseProgramadaDC objClaseProgramadaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClaseProgramada/ListarNombreInstructor", ReplyAction="http://tempuri.org/IServicioClaseProgramada/ListarNombreInstructorResponse")]
        System.Collections.Generic.List<ProxyClaseProgramada.ClaseProgramadaDC> ListarNombreInstructor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClaseProgramada/ListarNombreInstructor", ReplyAction="http://tempuri.org/IServicioClaseProgramada/ListarNombreInstructorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyClaseProgramada.ClaseProgramadaDC>> ListarNombreInstructorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClaseProgramada/ConsultarClaseProgramada", ReplyAction="http://tempuri.org/IServicioClaseProgramada/ConsultarClaseProgramadaResponse")]
        ProxyClaseProgramada.ClaseProgramadaDC ConsultarClaseProgramada(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClaseProgramada/ConsultarClaseProgramada", ReplyAction="http://tempuri.org/IServicioClaseProgramada/ConsultarClaseProgramadaResponse")]
        System.Threading.Tasks.Task<ProxyClaseProgramada.ClaseProgramadaDC> ConsultarClaseProgramadaAsync(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClaseProgramada/ConsultarClase_PorFecha", ReplyAction="http://tempuri.org/IServicioClaseProgramada/ConsultarClase_PorFechaResponse")]
        ProxyClaseProgramada.ClaseProgramadaDC ConsultarClase_PorFecha(System.DateTime strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClaseProgramada/ConsultarClase_PorFecha", ReplyAction="http://tempuri.org/IServicioClaseProgramada/ConsultarClase_PorFechaResponse")]
        System.Threading.Tasks.Task<ProxyClaseProgramada.ClaseProgramadaDC> ConsultarClase_PorFechaAsync(System.DateTime strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClaseProgramada/ListarClasesPorFecha", ReplyAction="http://tempuri.org/IServicioClaseProgramada/ListarClasesPorFechaResponse")]
        System.Collections.Generic.List<ProxyClaseProgramada.ClaseProgramadaDC> ListarClasesPorFecha(System.DateTime strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioClaseProgramada/ListarClasesPorFecha", ReplyAction="http://tempuri.org/IServicioClaseProgramada/ListarClasesPorFechaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyClaseProgramada.ClaseProgramadaDC>> ListarClasesPorFechaAsync(System.DateTime strId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioClaseProgramadaChannel : ProxyClaseProgramada.IServicioClaseProgramada, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioClaseProgramadaClient : System.ServiceModel.ClientBase<ProxyClaseProgramada.IServicioClaseProgramada>, ProxyClaseProgramada.IServicioClaseProgramada
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioClaseProgramadaClient() : 
                base(ServicioClaseProgramadaClient.GetDefaultBinding(), ServicioClaseProgramadaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioClaseProgramada.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClaseProgramadaClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioClaseProgramadaClient.GetBindingForEndpoint(endpointConfiguration), ServicioClaseProgramadaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClaseProgramadaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioClaseProgramadaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClaseProgramadaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioClaseProgramadaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClaseProgramadaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyClaseProgramada.ClaseProgramadaDC> ListarClaseProgramada()
        {
            return base.Channel.ListarClaseProgramada();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyClaseProgramada.ClaseProgramadaDC>> ListarClaseProgramadaAsync()
        {
            return base.Channel.ListarClaseProgramadaAsync();
        }
        
        public bool InsertarClaseProgramada(ProxyClaseProgramada.ClaseProgramadaDC objClaseProgramadaDC)
        {
            return base.Channel.InsertarClaseProgramada(objClaseProgramadaDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarClaseProgramadaAsync(ProxyClaseProgramada.ClaseProgramadaDC objClaseProgramadaDC)
        {
            return base.Channel.InsertarClaseProgramadaAsync(objClaseProgramadaDC);
        }
        
        public bool ActualizarClaseProgramada(ProxyClaseProgramada.ClaseProgramadaDC objClaseProgramadaDC)
        {
            return base.Channel.ActualizarClaseProgramada(objClaseProgramadaDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarClaseProgramadaAsync(ProxyClaseProgramada.ClaseProgramadaDC objClaseProgramadaDC)
        {
            return base.Channel.ActualizarClaseProgramadaAsync(objClaseProgramadaDC);
        }
        
        public System.Collections.Generic.List<ProxyClaseProgramada.ClaseProgramadaDC> ListarNombreInstructor()
        {
            return base.Channel.ListarNombreInstructor();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyClaseProgramada.ClaseProgramadaDC>> ListarNombreInstructorAsync()
        {
            return base.Channel.ListarNombreInstructorAsync();
        }
        
        public ProxyClaseProgramada.ClaseProgramadaDC ConsultarClaseProgramada(short strId)
        {
            return base.Channel.ConsultarClaseProgramada(strId);
        }
        
        public System.Threading.Tasks.Task<ProxyClaseProgramada.ClaseProgramadaDC> ConsultarClaseProgramadaAsync(short strId)
        {
            return base.Channel.ConsultarClaseProgramadaAsync(strId);
        }
        
        public ProxyClaseProgramada.ClaseProgramadaDC ConsultarClase_PorFecha(System.DateTime strId)
        {
            return base.Channel.ConsultarClase_PorFecha(strId);
        }
        
        public System.Threading.Tasks.Task<ProxyClaseProgramada.ClaseProgramadaDC> ConsultarClase_PorFechaAsync(System.DateTime strId)
        {
            return base.Channel.ConsultarClase_PorFechaAsync(strId);
        }
        
        public System.Collections.Generic.List<ProxyClaseProgramada.ClaseProgramadaDC> ListarClasesPorFecha(System.DateTime strId)
        {
            return base.Channel.ListarClasesPorFecha(strId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyClaseProgramada.ClaseProgramadaDC>> ListarClasesPorFechaAsync(System.DateTime strId)
        {
            return base.Channel.ListarClasesPorFechaAsync(strId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioClaseProgramada))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioClaseProgramada))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ReservaYoga/ServicioClasePrograma" +
                        "da/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioClaseProgramadaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioClaseProgramada);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioClaseProgramadaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioClaseProgramada);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioClaseProgramada,
        }
    }
}
