//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyUsuarioRol
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioRolDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ReservaYoga")]
    public partial class UsuarioRolDC : object
    {
        
        private string ApeMaternoField;
        
        private string ApePaternoField;
        
        private string ComentarioField;
        
        private string CorreoField;
        
        private string DepartamentoField;
        
        private string DireccionField;
        
        private string DistritoField;
        
        private string Dni_PersonalField;
        
        private short EstadoField;
        
        private System.DateTime Fec_RegField;
        
        private System.DateTime Fec_nacField;
        
        private short Id_RolField;
        
        private string Id_UbigeoField;
        
        private string NombreField;
        
        private string NombresField;
        
        private string Pass_UsuarioField;
        
        private string ProvinciaField;
        
        private string TelefonoField;
        
        private string Usu_RegField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeMaterno
        {
            get
            {
                return this.ApeMaternoField;
            }
            set
            {
                this.ApeMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePaterno
        {
            get
            {
                return this.ApePaternoField;
            }
            set
            {
                this.ApePaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comentario
        {
            get
            {
                return this.ComentarioField;
            }
            set
            {
                this.ComentarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                this.DistritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_Personal
        {
            get
            {
                return this.Dni_PersonalField;
            }
            set
            {
                this.Dni_PersonalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Reg
        {
            get
            {
                return this.Fec_RegField;
            }
            set
            {
                this.Fec_RegField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_nac
        {
            get
            {
                return this.Fec_nacField;
            }
            set
            {
                this.Fec_nacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Rol
        {
            get
            {
                return this.Id_RolField;
            }
            set
            {
                this.Id_RolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubigeo
        {
            get
            {
                return this.Id_UbigeoField;
            }
            set
            {
                this.Id_UbigeoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass_Usuario
        {
            get
            {
                return this.Pass_UsuarioField;
            }
            set
            {
                this.Pass_UsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Reg
        {
            get
            {
                return this.Usu_RegField;
            }
            set
            {
                this.Usu_RegField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUsuarioRol.IServicioUsuarioRol")]
    public interface IServicioUsuarioRol
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarioRol/InsertarUsuario", ReplyAction="http://tempuri.org/IServicioUsuarioRol/InsertarUsuarioResponse")]
        bool InsertarUsuario(ProxyUsuarioRol.UsuarioRolDC objUsuarioRolDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarioRol/InsertarUsuario", ReplyAction="http://tempuri.org/IServicioUsuarioRol/InsertarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> InsertarUsuarioAsync(ProxyUsuarioRol.UsuarioRolDC objUsuarioRolDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarioRol/ListarRol", ReplyAction="http://tempuri.org/IServicioUsuarioRol/ListarRolResponse")]
        System.Collections.Generic.List<ProxyUsuarioRol.UsuarioRolDC> ListarRol();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarioRol/ListarRol", ReplyAction="http://tempuri.org/IServicioUsuarioRol/ListarRolResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyUsuarioRol.UsuarioRolDC>> ListarRolAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioUsuarioRolChannel : ProxyUsuarioRol.IServicioUsuarioRol, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioUsuarioRolClient : System.ServiceModel.ClientBase<ProxyUsuarioRol.IServicioUsuarioRol>, ProxyUsuarioRol.IServicioUsuarioRol
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioUsuarioRolClient() : 
                base(ServicioUsuarioRolClient.GetDefaultBinding(), ServicioUsuarioRolClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioUsuarioRol.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioUsuarioRolClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioUsuarioRolClient.GetBindingForEndpoint(endpointConfiguration), ServicioUsuarioRolClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioUsuarioRolClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioUsuarioRolClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioUsuarioRolClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioUsuarioRolClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioUsuarioRolClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool InsertarUsuario(ProxyUsuarioRol.UsuarioRolDC objUsuarioRolDC)
        {
            return base.Channel.InsertarUsuario(objUsuarioRolDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarUsuarioAsync(ProxyUsuarioRol.UsuarioRolDC objUsuarioRolDC)
        {
            return base.Channel.InsertarUsuarioAsync(objUsuarioRolDC);
        }
        
        public System.Collections.Generic.List<ProxyUsuarioRol.UsuarioRolDC> ListarRol()
        {
            return base.Channel.ListarRol();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyUsuarioRol.UsuarioRolDC>> ListarRolAsync()
        {
            return base.Channel.ListarRolAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioUsuarioRol))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioUsuarioRol))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ReservaYoga/ServicioUsuarioRol/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioUsuarioRolClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioUsuarioRol);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioUsuarioRolClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioUsuarioRol);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioUsuarioRol,
        }
    }
}
