//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyInstructorDisciplina
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstructorDisciplinaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ReservaYoga")]
    public partial class InstructorDisciplinaDC : object
    {
        
        private string Cod_dispField;
        
        private string Id_Inst_DispField;
        
        private string Id_InstructorField;
        
        private string NombreDisciplinaField;
        
        private string NombreInstructorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_disp
        {
            get
            {
                return this.Cod_dispField;
            }
            set
            {
                this.Cod_dispField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Inst_Disp
        {
            get
            {
                return this.Id_Inst_DispField;
            }
            set
            {
                this.Id_Inst_DispField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Instructor
        {
            get
            {
                return this.Id_InstructorField;
            }
            set
            {
                this.Id_InstructorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDisciplina
        {
            get
            {
                return this.NombreDisciplinaField;
            }
            set
            {
                this.NombreDisciplinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreInstructor
        {
            get
            {
                return this.NombreInstructorField;
            }
            set
            {
                this.NombreInstructorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyInstructorDisciplina.IServicioInstructorDisciplina")]
    public interface IServicioInstructorDisciplina
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructorDisciplina/Instructor", ReplyAction="http://tempuri.org/IServicioInstructorDisciplina/InstructorResponse")]
        System.Collections.Generic.List<ProxyInstructorDisciplina.InstructorDisciplinaDC> Instructor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructorDisciplina/Instructor", ReplyAction="http://tempuri.org/IServicioInstructorDisciplina/InstructorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyInstructorDisciplina.InstructorDisciplinaDC>> InstructorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructorDisciplina/Instructor_Disciplina_Combo", ReplyAction="http://tempuri.org/IServicioInstructorDisciplina/Instructor_Disciplina_ComboRespo" +
            "nse")]
        System.Collections.Generic.List<ProxyInstructorDisciplina.InstructorDisciplinaDC> Instructor_Disciplina_Combo(string Id_Instructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructorDisciplina/Instructor_Disciplina_Combo", ReplyAction="http://tempuri.org/IServicioInstructorDisciplina/Instructor_Disciplina_ComboRespo" +
            "nse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyInstructorDisciplina.InstructorDisciplinaDC>> Instructor_Disciplina_ComboAsync(string Id_Instructor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioInstructorDisciplinaChannel : ProxyInstructorDisciplina.IServicioInstructorDisciplina, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioInstructorDisciplinaClient : System.ServiceModel.ClientBase<ProxyInstructorDisciplina.IServicioInstructorDisciplina>, ProxyInstructorDisciplina.IServicioInstructorDisciplina
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioInstructorDisciplinaClient() : 
                base(ServicioInstructorDisciplinaClient.GetDefaultBinding(), ServicioInstructorDisciplinaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioInstructorDisciplina.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioInstructorDisciplinaClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioInstructorDisciplinaClient.GetBindingForEndpoint(endpointConfiguration), ServicioInstructorDisciplinaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioInstructorDisciplinaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioInstructorDisciplinaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioInstructorDisciplinaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioInstructorDisciplinaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioInstructorDisciplinaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyInstructorDisciplina.InstructorDisciplinaDC> Instructor()
        {
            return base.Channel.Instructor();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyInstructorDisciplina.InstructorDisciplinaDC>> InstructorAsync()
        {
            return base.Channel.InstructorAsync();
        }
        
        public System.Collections.Generic.List<ProxyInstructorDisciplina.InstructorDisciplinaDC> Instructor_Disciplina_Combo(string Id_Instructor)
        {
            return base.Channel.Instructor_Disciplina_Combo(Id_Instructor);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyInstructorDisciplina.InstructorDisciplinaDC>> Instructor_Disciplina_ComboAsync(string Id_Instructor)
        {
            return base.Channel.Instructor_Disciplina_ComboAsync(Id_Instructor);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioInstructorDisciplina))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioInstructorDisciplina))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ReservaYoga/ServicioInstructorDis" +
                        "ciplina/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioInstructorDisciplinaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioInstructorDisciplina);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioInstructorDisciplinaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioInstructorDisciplina);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioInstructorDisciplina,
        }
    }
}
