//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyInstructor
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstructorDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ReservaYoga")]
    public partial class InstructorDC : object
    {
        
        private string ApeMaternoField;
        
        private string ApePaternoField;
        
        private string CorreoField;
        
        private string DepartamentoField;
        
        private string Dir_instField;
        
        private string DistritoField;
        
        private string Dni_instField;
        
        private short Est_insField;
        
        private string EstadoInstField;
        
        private System.DateTime Fec_Ult_ModField;
        
        private System.DateTime Fec_nacField;
        
        private System.DateTime Fec_regField;
        
        private string FotoField;
        
        private string Id_InstructorField;
        
        private string Id_UbigeoField;
        
        private string NombreField;
        
        private string NombreInstructorField;
        
        private string ProvinciaField;
        
        private string Tel_instField;
        
        private string Usu_Ult_ModField;
        
        private string Usu_regField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeMaterno
        {
            get
            {
                return this.ApeMaternoField;
            }
            set
            {
                this.ApeMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePaterno
        {
            get
            {
                return this.ApePaternoField;
            }
            set
            {
                this.ApePaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dir_inst
        {
            get
            {
                return this.Dir_instField;
            }
            set
            {
                this.Dir_instField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                this.DistritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_inst
        {
            get
            {
                return this.Dni_instField;
            }
            set
            {
                this.Dni_instField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_ins
        {
            get
            {
                return this.Est_insField;
            }
            set
            {
                this.Est_insField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoInst
        {
            get
            {
                return this.EstadoInstField;
            }
            set
            {
                this.EstadoInstField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod
        {
            get
            {
                return this.Fec_Ult_ModField;
            }
            set
            {
                this.Fec_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_nac
        {
            get
            {
                return this.Fec_nacField;
            }
            set
            {
                this.Fec_nacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_reg
        {
            get
            {
                return this.Fec_regField;
            }
            set
            {
                this.Fec_regField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foto
        {
            get
            {
                return this.FotoField;
            }
            set
            {
                this.FotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Instructor
        {
            get
            {
                return this.Id_InstructorField;
            }
            set
            {
                this.Id_InstructorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubigeo
        {
            get
            {
                return this.Id_UbigeoField;
            }
            set
            {
                this.Id_UbigeoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreInstructor
        {
            get
            {
                return this.NombreInstructorField;
            }
            set
            {
                this.NombreInstructorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_inst
        {
            get
            {
                return this.Tel_instField;
            }
            set
            {
                this.Tel_instField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod
        {
            get
            {
                return this.Usu_Ult_ModField;
            }
            set
            {
                this.Usu_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_reg
        {
            get
            {
                return this.Usu_regField;
            }
            set
            {
                this.Usu_regField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyInstructor.IServicioInstructor")]
    public interface IServicioInstructor
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/InsertarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/InsertarInstructorResponse")]
        bool InsertarInstructor(ProxyInstructor.InstructorDC objInstructorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/InsertarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/InsertarInstructorResponse")]
        System.Threading.Tasks.Task<bool> InsertarInstructorAsync(ProxyInstructor.InstructorDC objInstructorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/ActualizarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/ActualizarInstructorResponse")]
        bool ActualizarInstructor(ProxyInstructor.InstructorDC objInstructorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/ActualizarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/ActualizarInstructorResponse")]
        System.Threading.Tasks.Task<bool> ActualizarInstructorAsync(ProxyInstructor.InstructorDC objInstructorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/EliminarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/EliminarInstructorResponse")]
        bool EliminarInstructor(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/EliminarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/EliminarInstructorResponse")]
        System.Threading.Tasks.Task<bool> EliminarInstructorAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/ConsultarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/ConsultarInstructorResponse")]
        ProxyInstructor.InstructorDC ConsultarInstructor(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/ConsultarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/ConsultarInstructorResponse")]
        System.Threading.Tasks.Task<ProxyInstructor.InstructorDC> ConsultarInstructorAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/ListarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/ListarInstructorResponse")]
        System.Collections.Generic.List<ProxyInstructor.InstructorDC> ListarInstructor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/ListarInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/ListarInstructorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyInstructor.InstructorDC>> ListarInstructorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/ListarNombreInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/ListarNombreInstructorResponse")]
        System.Collections.Generic.List<ProxyInstructor.InstructorDC> ListarNombreInstructor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioInstructor/ListarNombreInstructor", ReplyAction="http://tempuri.org/IServicioInstructor/ListarNombreInstructorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyInstructor.InstructorDC>> ListarNombreInstructorAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioInstructorChannel : ProxyInstructor.IServicioInstructor, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioInstructorClient : System.ServiceModel.ClientBase<ProxyInstructor.IServicioInstructor>, ProxyInstructor.IServicioInstructor
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioInstructorClient() : 
                base(ServicioInstructorClient.GetDefaultBinding(), ServicioInstructorClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioInstructor.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioInstructorClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioInstructorClient.GetBindingForEndpoint(endpointConfiguration), ServicioInstructorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioInstructorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioInstructorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioInstructorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioInstructorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioInstructorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool InsertarInstructor(ProxyInstructor.InstructorDC objInstructorDC)
        {
            return base.Channel.InsertarInstructor(objInstructorDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarInstructorAsync(ProxyInstructor.InstructorDC objInstructorDC)
        {
            return base.Channel.InsertarInstructorAsync(objInstructorDC);
        }
        
        public bool ActualizarInstructor(ProxyInstructor.InstructorDC objInstructorDC)
        {
            return base.Channel.ActualizarInstructor(objInstructorDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarInstructorAsync(ProxyInstructor.InstructorDC objInstructorDC)
        {
            return base.Channel.ActualizarInstructorAsync(objInstructorDC);
        }
        
        public bool EliminarInstructor(string strCodigo)
        {
            return base.Channel.EliminarInstructor(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarInstructorAsync(string strCodigo)
        {
            return base.Channel.EliminarInstructorAsync(strCodigo);
        }
        
        public ProxyInstructor.InstructorDC ConsultarInstructor(string strCodigo)
        {
            return base.Channel.ConsultarInstructor(strCodigo);
        }
        
        public System.Threading.Tasks.Task<ProxyInstructor.InstructorDC> ConsultarInstructorAsync(string strCodigo)
        {
            return base.Channel.ConsultarInstructorAsync(strCodigo);
        }
        
        public System.Collections.Generic.List<ProxyInstructor.InstructorDC> ListarInstructor()
        {
            return base.Channel.ListarInstructor();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyInstructor.InstructorDC>> ListarInstructorAsync()
        {
            return base.Channel.ListarInstructorAsync();
        }
        
        public System.Collections.Generic.List<ProxyInstructor.InstructorDC> ListarNombreInstructor()
        {
            return base.Channel.ListarNombreInstructor();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyInstructor.InstructorDC>> ListarNombreInstructorAsync()
        {
            return base.Channel.ListarNombreInstructorAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioInstructor))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioInstructor))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ReservaYoga/ServicioInstructor/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioInstructorClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioInstructor);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioInstructorClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioInstructor);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioInstructor,
        }
    }
}
