//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyDisciplina
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisciplinaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ReservaYoga")]
    public partial class DisciplinaDC : object
    {
        
        private string CategoriaField;
        
        private string Cod_dispField;
        
        private string ComentarioField;
        
        private string DuracionField;
        
        private short EstadoField;
        
        private short Id_CatField;
        
        private string IntensidadField;
        
        private string NombreField;
        
        private float PrecioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categoria
        {
            get
            {
                return this.CategoriaField;
            }
            set
            {
                this.CategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_disp
        {
            get
            {
                return this.Cod_dispField;
            }
            set
            {
                this.Cod_dispField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comentario
        {
            get
            {
                return this.ComentarioField;
            }
            set
            {
                this.ComentarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Duracion
        {
            get
            {
                return this.DuracionField;
            }
            set
            {
                this.DuracionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Cat
        {
            get
            {
                return this.Id_CatField;
            }
            set
            {
                this.Id_CatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Intensidad
        {
            get
            {
                return this.IntensidadField;
            }
            set
            {
                this.IntensidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Precio
        {
            get
            {
                return this.PrecioField;
            }
            set
            {
                this.PrecioField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyDisciplina.IServicioDisciplina")]
    public interface IServicioDisciplina
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDisciplina/InsertarDisciplina", ReplyAction="http://tempuri.org/IServicioDisciplina/InsertarDisciplinaResponse")]
        bool InsertarDisciplina(ProxyDisciplina.DisciplinaDC objDisciplinaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDisciplina/InsertarDisciplina", ReplyAction="http://tempuri.org/IServicioDisciplina/InsertarDisciplinaResponse")]
        System.Threading.Tasks.Task<bool> InsertarDisciplinaAsync(ProxyDisciplina.DisciplinaDC objDisciplinaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDisciplina/ActualizarDisciplina", ReplyAction="http://tempuri.org/IServicioDisciplina/ActualizarDisciplinaResponse")]
        bool ActualizarDisciplina(ProxyDisciplina.DisciplinaDC objDisciplinaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDisciplina/ActualizarDisciplina", ReplyAction="http://tempuri.org/IServicioDisciplina/ActualizarDisciplinaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarDisciplinaAsync(ProxyDisciplina.DisciplinaDC objDisciplinaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDisciplina/EliminarDisciplina", ReplyAction="http://tempuri.org/IServicioDisciplina/EliminarDisciplinaResponse")]
        bool EliminarDisciplina(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDisciplina/EliminarDisciplina", ReplyAction="http://tempuri.org/IServicioDisciplina/EliminarDisciplinaResponse")]
        System.Threading.Tasks.Task<bool> EliminarDisciplinaAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDisciplina/ListarDisciplina", ReplyAction="http://tempuri.org/IServicioDisciplina/ListarDisciplinaResponse")]
        System.Collections.Generic.List<ProxyDisciplina.DisciplinaDC> ListarDisciplina();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDisciplina/ListarDisciplina", ReplyAction="http://tempuri.org/IServicioDisciplina/ListarDisciplinaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyDisciplina.DisciplinaDC>> ListarDisciplinaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDisciplina/ConsultarDisciplina", ReplyAction="http://tempuri.org/IServicioDisciplina/ConsultarDisciplinaResponse")]
        ProxyDisciplina.DisciplinaDC ConsultarDisciplina(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDisciplina/ConsultarDisciplina", ReplyAction="http://tempuri.org/IServicioDisciplina/ConsultarDisciplinaResponse")]
        System.Threading.Tasks.Task<ProxyDisciplina.DisciplinaDC> ConsultarDisciplinaAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDisciplina/ListarCategoria", ReplyAction="http://tempuri.org/IServicioDisciplina/ListarCategoriaResponse")]
        System.Collections.Generic.List<ProxyDisciplina.DisciplinaDC> ListarCategoria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDisciplina/ListarCategoria", ReplyAction="http://tempuri.org/IServicioDisciplina/ListarCategoriaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyDisciplina.DisciplinaDC>> ListarCategoriaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDisciplina/UpdateDisciplinaEstado", ReplyAction="http://tempuri.org/IServicioDisciplina/UpdateDisciplinaEstadoResponse")]
        bool UpdateDisciplinaEstado(ProxyDisciplina.DisciplinaDC objDisciplinaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDisciplina/UpdateDisciplinaEstado", ReplyAction="http://tempuri.org/IServicioDisciplina/UpdateDisciplinaEstadoResponse")]
        System.Threading.Tasks.Task<bool> UpdateDisciplinaEstadoAsync(ProxyDisciplina.DisciplinaDC objDisciplinaDC);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioDisciplinaChannel : ProxyDisciplina.IServicioDisciplina, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioDisciplinaClient : System.ServiceModel.ClientBase<ProxyDisciplina.IServicioDisciplina>, ProxyDisciplina.IServicioDisciplina
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioDisciplinaClient() : 
                base(ServicioDisciplinaClient.GetDefaultBinding(), ServicioDisciplinaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioDisciplina.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioDisciplinaClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioDisciplinaClient.GetBindingForEndpoint(endpointConfiguration), ServicioDisciplinaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioDisciplinaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioDisciplinaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioDisciplinaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioDisciplinaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioDisciplinaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool InsertarDisciplina(ProxyDisciplina.DisciplinaDC objDisciplinaDC)
        {
            return base.Channel.InsertarDisciplina(objDisciplinaDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarDisciplinaAsync(ProxyDisciplina.DisciplinaDC objDisciplinaDC)
        {
            return base.Channel.InsertarDisciplinaAsync(objDisciplinaDC);
        }
        
        public bool ActualizarDisciplina(ProxyDisciplina.DisciplinaDC objDisciplinaDC)
        {
            return base.Channel.ActualizarDisciplina(objDisciplinaDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarDisciplinaAsync(ProxyDisciplina.DisciplinaDC objDisciplinaDC)
        {
            return base.Channel.ActualizarDisciplinaAsync(objDisciplinaDC);
        }
        
        public bool EliminarDisciplina(string strCodigo)
        {
            return base.Channel.EliminarDisciplina(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarDisciplinaAsync(string strCodigo)
        {
            return base.Channel.EliminarDisciplinaAsync(strCodigo);
        }
        
        public System.Collections.Generic.List<ProxyDisciplina.DisciplinaDC> ListarDisciplina()
        {
            return base.Channel.ListarDisciplina();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyDisciplina.DisciplinaDC>> ListarDisciplinaAsync()
        {
            return base.Channel.ListarDisciplinaAsync();
        }
        
        public ProxyDisciplina.DisciplinaDC ConsultarDisciplina(string strCodigo)
        {
            return base.Channel.ConsultarDisciplina(strCodigo);
        }
        
        public System.Threading.Tasks.Task<ProxyDisciplina.DisciplinaDC> ConsultarDisciplinaAsync(string strCodigo)
        {
            return base.Channel.ConsultarDisciplinaAsync(strCodigo);
        }
        
        public System.Collections.Generic.List<ProxyDisciplina.DisciplinaDC> ListarCategoria()
        {
            return base.Channel.ListarCategoria();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyDisciplina.DisciplinaDC>> ListarCategoriaAsync()
        {
            return base.Channel.ListarCategoriaAsync();
        }
        
        public bool UpdateDisciplinaEstado(ProxyDisciplina.DisciplinaDC objDisciplinaDC)
        {
            return base.Channel.UpdateDisciplinaEstado(objDisciplinaDC);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateDisciplinaEstadoAsync(ProxyDisciplina.DisciplinaDC objDisciplinaDC)
        {
            return base.Channel.UpdateDisciplinaEstadoAsync(objDisciplinaDC);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioDisciplina))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioDisciplina))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ReservaYoga/ServicioDisciplina/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioDisciplinaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioDisciplina);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioDisciplinaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioDisciplina);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioDisciplina,
        }
    }
}
