//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UbigeoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ReservaYoga")]
    public partial class UbigeoDC : object
    {
        
        private string DepartamentoField;
        
        private string DistritoField;
        
        private string IdDepaField;
        
        private string IdDistField;
        
        private string IdProvField;
        
        private string Id_UbigeoField;
        
        private string ProvinciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                this.DistritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDepa
        {
            get
            {
                return this.IdDepaField;
            }
            set
            {
                this.IdDepaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDist
        {
            get
            {
                return this.IdDistField;
            }
            set
            {
                this.IdDistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProv
        {
            get
            {
                return this.IdProvField;
            }
            set
            {
                this.IdProvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubigeo
        {
            get
            {
                return this.Id_UbigeoField;
            }
            set
            {
                this.Id_UbigeoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServicioUbigeo")]
    public interface IServicioUbigeo
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/Ubigeo_Departamentos", ReplyAction="http://tempuri.org/IServicioUbigeo/Ubigeo_DepartamentosResponse")]
        System.Collections.Generic.List<ServiceReference1.UbigeoDC> Ubigeo_Departamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/Ubigeo_Departamentos", ReplyAction="http://tempuri.org/IServicioUbigeo/Ubigeo_DepartamentosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.UbigeoDC>> Ubigeo_DepartamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/Ubigeo_ProvinciasDepartamento", ReplyAction="http://tempuri.org/IServicioUbigeo/Ubigeo_ProvinciasDepartamentoResponse")]
        System.Collections.Generic.List<ServiceReference1.UbigeoDC> Ubigeo_ProvinciasDepartamento(string IdDepa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/Ubigeo_ProvinciasDepartamento", ReplyAction="http://tempuri.org/IServicioUbigeo/Ubigeo_ProvinciasDepartamentoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.UbigeoDC>> Ubigeo_ProvinciasDepartamentoAsync(string IdDepa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/Ubigeo_DistritosProvinciaDepartamento", ReplyAction="http://tempuri.org/IServicioUbigeo/Ubigeo_DistritosProvinciaDepartamentoResponse")]
        System.Collections.Generic.List<ServiceReference1.UbigeoDC> Ubigeo_DistritosProvinciaDepartamento(string IdDepa, string IdProv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/Ubigeo_DistritosProvinciaDepartamento", ReplyAction="http://tempuri.org/IServicioUbigeo/Ubigeo_DistritosProvinciaDepartamentoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.UbigeoDC>> Ubigeo_DistritosProvinciaDepartamentoAsync(string IdDepa, string IdProv);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioUbigeoChannel : ServiceReference1.IServicioUbigeo, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioUbigeoClient : System.ServiceModel.ClientBase<ServiceReference1.IServicioUbigeo>, ServiceReference1.IServicioUbigeo
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioUbigeoClient() : 
                base(ServicioUbigeoClient.GetDefaultBinding(), ServicioUbigeoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioUbigeo.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioUbigeoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioUbigeoClient.GetBindingForEndpoint(endpointConfiguration), ServicioUbigeoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioUbigeoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioUbigeoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioUbigeoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioUbigeoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioUbigeoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ServiceReference1.UbigeoDC> Ubigeo_Departamentos()
        {
            return base.Channel.Ubigeo_Departamentos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.UbigeoDC>> Ubigeo_DepartamentosAsync()
        {
            return base.Channel.Ubigeo_DepartamentosAsync();
        }
        
        public System.Collections.Generic.List<ServiceReference1.UbigeoDC> Ubigeo_ProvinciasDepartamento(string IdDepa)
        {
            return base.Channel.Ubigeo_ProvinciasDepartamento(IdDepa);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.UbigeoDC>> Ubigeo_ProvinciasDepartamentoAsync(string IdDepa)
        {
            return base.Channel.Ubigeo_ProvinciasDepartamentoAsync(IdDepa);
        }
        
        public System.Collections.Generic.List<ServiceReference1.UbigeoDC> Ubigeo_DistritosProvinciaDepartamento(string IdDepa, string IdProv)
        {
            return base.Channel.Ubigeo_DistritosProvinciaDepartamento(IdDepa, IdProv);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.UbigeoDC>> Ubigeo_DistritosProvinciaDepartamentoAsync(string IdDepa, string IdProv)
        {
            return base.Channel.Ubigeo_DistritosProvinciaDepartamentoAsync(IdDepa, IdProv);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioUbigeo))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioUbigeo))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_ReservaYoga/ServicioUbigeo/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioUbigeoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioUbigeo);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioUbigeoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioUbigeo);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioUbigeo,
        }
    }
}
