//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_ConsultaInstructor.ProxyCliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ReservaYoga")]
    [System.SerializableAttribute()]
    public partial class ClienteDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApePaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dir_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dni_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Est_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoTextoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_nacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_regField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Id_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoTextoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tel_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_regField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeMaterno {
            get {
                return this.ApeMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeMaternoField, value) != true)) {
                    this.ApeMaternoField = value;
                    this.RaisePropertyChanged("ApeMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePaterno {
            get {
                return this.ApePaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApePaternoField, value) != true)) {
                    this.ApePaternoField = value;
                    this.RaisePropertyChanged("ApePaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dir_cli {
            get {
                return this.Dir_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Dir_cliField, value) != true)) {
                    this.Dir_cliField = value;
                    this.RaisePropertyChanged("Dir_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_cli {
            get {
                return this.Dni_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Dni_cliField, value) != true)) {
                    this.Dni_cliField = value;
                    this.RaisePropertyChanged("Dni_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_cli {
            get {
                return this.Est_cliField;
            }
            set {
                if ((this.Est_cliField.Equals(value) != true)) {
                    this.Est_cliField = value;
                    this.RaisePropertyChanged("Est_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoTexto {
            get {
                return this.EstadoTextoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoTextoField, value) != true)) {
                    this.EstadoTextoField = value;
                    this.RaisePropertyChanged("EstadoTexto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_nac {
            get {
                return this.Fec_nacField;
            }
            set {
                if ((this.Fec_nacField.Equals(value) != true)) {
                    this.Fec_nacField = value;
                    this.RaisePropertyChanged("Fec_nac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_reg {
            get {
                return this.Fec_regField;
            }
            set {
                if ((this.Fec_regField.Equals(value) != true)) {
                    this.Fec_regField = value;
                    this.RaisePropertyChanged("Fec_reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Cliente {
            get {
                return this.Id_ClienteField;
            }
            set {
                if ((this.Id_ClienteField.Equals(value) != true)) {
                    this.Id_ClienteField = value;
                    this.RaisePropertyChanged("Id_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubigeo {
            get {
                return this.Id_UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_UbigeoField, value) != true)) {
                    this.Id_UbigeoField = value;
                    this.RaisePropertyChanged("Id_Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SexoTexto {
            get {
                return this.SexoTextoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoTextoField, value) != true)) {
                    this.SexoTextoField = value;
                    this.RaisePropertyChanged("SexoTexto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_cli {
            get {
                return this.Tel_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Tel_cliField, value) != true)) {
                    this.Tel_cliField = value;
                    this.RaisePropertyChanged("Tel_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_reg {
            get {
                return this.Usu_regField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_regField, value) != true)) {
                    this.Usu_regField = value;
                    this.RaisePropertyChanged("Usu_reg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCliente.IServicioCliente")]
    public interface IServicioCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        bool InsertarCliente(WEB_ConsultaInstructor.ProxyCliente.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        System.Threading.Tasks.Task<bool> InsertarClienteAsync(WEB_ConsultaInstructor.ProxyCliente.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        bool ActualizarCliente(WEB_ConsultaInstructor.ProxyCliente.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        System.Threading.Tasks.Task<bool> ActualizarClienteAsync(WEB_ConsultaInstructor.ProxyCliente.ClienteDC objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EliminarCliente", ReplyAction="http://tempuri.org/IServicioCliente/EliminarClienteResponse")]
        bool EliminarCliente(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EliminarCliente", ReplyAction="http://tempuri.org/IServicioCliente/EliminarClienteResponse")]
        System.Threading.Tasks.Task<bool> EliminarClienteAsync(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        WEB_ConsultaInstructor.ProxyCliente.ClienteDC ConsultarCliente(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        System.Threading.Tasks.Task<WEB_ConsultaInstructor.ProxyCliente.ClienteDC> ConsultarClienteAsync(short strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteResponse")]
        WEB_ConsultaInstructor.ProxyCliente.ClienteDC[] ListarCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteResponse")]
        System.Threading.Tasks.Task<WEB_ConsultaInstructor.ProxyCliente.ClienteDC[]> ListarClienteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioClienteChannel : WEB_ConsultaInstructor.ProxyCliente.IServicioCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClienteClient : System.ServiceModel.ClientBase<WEB_ConsultaInstructor.ProxyCliente.IServicioCliente>, WEB_ConsultaInstructor.ProxyCliente.IServicioCliente {
        
        public ServicioClienteClient() {
        }
        
        public ServicioClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertarCliente(WEB_ConsultaInstructor.ProxyCliente.ClienteDC objClienteDC) {
            return base.Channel.InsertarCliente(objClienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarClienteAsync(WEB_ConsultaInstructor.ProxyCliente.ClienteDC objClienteDC) {
            return base.Channel.InsertarClienteAsync(objClienteDC);
        }
        
        public bool ActualizarCliente(WEB_ConsultaInstructor.ProxyCliente.ClienteDC objClienteDC) {
            return base.Channel.ActualizarCliente(objClienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarClienteAsync(WEB_ConsultaInstructor.ProxyCliente.ClienteDC objClienteDC) {
            return base.Channel.ActualizarClienteAsync(objClienteDC);
        }
        
        public bool EliminarCliente(short strId) {
            return base.Channel.EliminarCliente(strId);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarClienteAsync(short strId) {
            return base.Channel.EliminarClienteAsync(strId);
        }
        
        public WEB_ConsultaInstructor.ProxyCliente.ClienteDC ConsultarCliente(short strId) {
            return base.Channel.ConsultarCliente(strId);
        }
        
        public System.Threading.Tasks.Task<WEB_ConsultaInstructor.ProxyCliente.ClienteDC> ConsultarClienteAsync(short strId) {
            return base.Channel.ConsultarClienteAsync(strId);
        }
        
        public WEB_ConsultaInstructor.ProxyCliente.ClienteDC[] ListarCliente() {
            return base.Channel.ListarCliente();
        }
        
        public System.Threading.Tasks.Task<WEB_ConsultaInstructor.ProxyCliente.ClienteDC[]> ListarClienteAsync() {
            return base.Channel.ListarClienteAsync();
        }
    }
}
