//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_ConsultaInstructor.ProxyConsultaClase {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_ReservaYoga")]
    [System.SerializableAttribute()]
    public partial class ConsultaDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Est_claseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoClaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_ClaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Hora_EmpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Hora_TermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Id_SalonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreSalonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_clase {
            get {
                return this.Est_claseField;
            }
            set {
                if ((this.Est_claseField.Equals(value) != true)) {
                    this.Est_claseField = value;
                    this.RaisePropertyChanged("Est_clase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoClase {
            get {
                return this.EstadoClaseField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoClaseField, value) != true)) {
                    this.EstadoClaseField = value;
                    this.RaisePropertyChanged("EstadoClase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Clase {
            get {
                return this.Fec_ClaseField;
            }
            set {
                if ((this.Fec_ClaseField.Equals(value) != true)) {
                    this.Fec_ClaseField = value;
                    this.RaisePropertyChanged("Fec_Clase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Hora_Emp {
            get {
                return this.Hora_EmpField;
            }
            set {
                if ((this.Hora_EmpField.Equals(value) != true)) {
                    this.Hora_EmpField = value;
                    this.RaisePropertyChanged("Hora_Emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Hora_Term {
            get {
                return this.Hora_TermField;
            }
            set {
                if ((this.Hora_TermField.Equals(value) != true)) {
                    this.Hora_TermField = value;
                    this.RaisePropertyChanged("Hora_Term");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id_Salon {
            get {
                return this.Id_SalonField;
            }
            set {
                if ((this.Id_SalonField.Equals(value) != true)) {
                    this.Id_SalonField = value;
                    this.RaisePropertyChanged("Id_Salon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreSalon {
            get {
                return this.NombreSalonField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreSalonField, value) != true)) {
                    this.NombreSalonField = value;
                    this.RaisePropertyChanged("NombreSalon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyConsultaClase.IConsultaInstructorClases")]
    public interface IConsultaInstructorClases {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaInstructorClases/ListarClasesProgramadasInstructor", ReplyAction="http://tempuri.org/IConsultaInstructorClases/ListarClasesProgramadasInstructorRes" +
            "ponse")]
        WEB_ConsultaInstructor.ProxyConsultaClase.ConsultaDC[] ListarClasesProgramadasInstructor(string strCodigo, System.DateTime fecIni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaInstructorClases/ListarClasesProgramadasInstructor", ReplyAction="http://tempuri.org/IConsultaInstructorClases/ListarClasesProgramadasInstructorRes" +
            "ponse")]
        System.Threading.Tasks.Task<WEB_ConsultaInstructor.ProxyConsultaClase.ConsultaDC[]> ListarClasesProgramadasInstructorAsync(string strCodigo, System.DateTime fecIni);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsultaInstructorClasesChannel : WEB_ConsultaInstructor.ProxyConsultaClase.IConsultaInstructorClases, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaInstructorClasesClient : System.ServiceModel.ClientBase<WEB_ConsultaInstructor.ProxyConsultaClase.IConsultaInstructorClases>, WEB_ConsultaInstructor.ProxyConsultaClase.IConsultaInstructorClases {
        
        public ConsultaInstructorClasesClient() {
        }
        
        public ConsultaInstructorClasesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaInstructorClasesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaInstructorClasesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaInstructorClasesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WEB_ConsultaInstructor.ProxyConsultaClase.ConsultaDC[] ListarClasesProgramadasInstructor(string strCodigo, System.DateTime fecIni) {
            return base.Channel.ListarClasesProgramadasInstructor(strCodigo, fecIni);
        }
        
        public System.Threading.Tasks.Task<WEB_ConsultaInstructor.ProxyConsultaClase.ConsultaDC[]> ListarClasesProgramadasInstructorAsync(string strCodigo, System.DateTime fecIni) {
            return base.Channel.ListarClasesProgramadasInstructorAsync(strCodigo, fecIni);
        }
    }
}
